// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sqleditor} from '../models';

export function AnalyzeSqlSemantics(arg1:string,arg2:Array<sqleditor.ResolvedRef>,arg3:Array<sqleditor.ColEntry>):Promise<Array<sqleditor.DiagMarker>>;

export function AnalyzeSqlSyntax(arg1:string):Promise<Array<sqleditor.DiagMarker>>;

export function ApplySqlCasing(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ComputeGitLineDiff(arg1:Array<string>,arg2:Array<string>,arg3:number):Promise<sqleditor.LineDiff>;

export function ComputeJoinOnConditions(arg1:sqleditor.JoinOnSuggestionsReq):Promise<Array<sqleditor.JoinCondition>>;

export function FromSourceCount(arg1:string):Promise<number>;

export function GetActiveFunctionCall(arg1:string):Promise<sqleditor.FunctionCallContext>;

export function GetAutocompleteContextFull(arg1:sqleditor.AutocompleteContextRequest):Promise<sqleditor.AutocompleteContext>;

export function GetIdentifierAtColumn(arg1:string,arg2:number):Promise<Array<string>>;

export function GetSnowflakeKeywords():Promise<Array<string>>;

export function GetSqlStatementRanges(arg1:string):Promise<Array<sqleditor.StatementRange>>;

export function ParseJoinTableRefs(arg1:string):Promise<Array<sqleditor.JoinTableRef>>;

export function ParseSignatureParams(arg1:string):Promise<Array<sqleditor.SignatureParam>>;

export function ResolveTableRefs(arg1:Array<sqleditor.JoinTableRef>,arg2:Array<sqleditor.StoreObject>,arg3:sqleditor.UseContext,arg4:sqleditor.SessionContext):Promise<Array<sqleditor.ResolvedRef>>;

export function StarSelectAt(arg1:string,arg2:number,arg3:number):Promise<sqleditor.StarSelect>;

export function ValidateAntiPatterns(arg1:string,arg2:Array<sqleditor.StatementRange>):Promise<Array<sqleditor.DiagMarker>>;

export function ValidateBareColumnRefs(arg1:sqleditor.ValidateBareColsRequest):Promise<Array<sqleditor.DiagMarker>>;

export function ValidateDataTypes(arg1:string,arg2:Array<sqleditor.StatementRange>):Promise<Array<sqleditor.DiagMarker>>;

export function ValidateGrammar(arg1:string,arg2:Array<sqleditor.StatementRange>):Promise<Array<sqleditor.DiagMarker>>;

export function ValidateTablesExist(arg1:sqleditor.ValidateTablesExistRequest):Promise<Array<sqleditor.DiagMarker>>;
