// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSqlSemantics(arg1, arg2, arg3) {
  return window['go']['sqleditor']['Service']['AnalyzeSqlSemantics'](arg1, arg2, arg3);
}

export function AnalyzeSqlSyntax(arg1) {
  return window['go']['sqleditor']['Service']['AnalyzeSqlSyntax'](arg1);
}

export function ApplySqlCasing(arg1, arg2, arg3, arg4) {
  return window['go']['sqleditor']['Service']['ApplySqlCasing'](arg1, arg2, arg3, arg4);
}

export function ComputeJoinOnConditions(arg1) {
  return window['go']['sqleditor']['Service']['ComputeJoinOnConditions'](arg1);
}

export function GetActiveFunctionCall(arg1) {
  return window['go']['sqleditor']['Service']['GetActiveFunctionCall'](arg1);
}

export function GetIdentifierAtColumn(arg1, arg2) {
  return window['go']['sqleditor']['Service']['GetIdentifierAtColumn'](arg1, arg2);
}

export function GetScriptingCompletions(arg1, arg2) {
  return window['go']['sqleditor']['Service']['GetScriptingCompletions'](arg1, arg2);
}

export function GetSnowflakeKeywords() {
  return window['go']['sqleditor']['Service']['GetSnowflakeKeywords']();
}

export function GetSqlStatementRanges(arg1) {
  return window['go']['sqleditor']['Service']['GetSqlStatementRanges'](arg1);
}

export function ParseJoinTableRefs(arg1) {
  return window['go']['sqleditor']['Service']['ParseJoinTableRefs'](arg1);
}

export function ParseSignatureParams(arg1) {
  return window['go']['sqleditor']['Service']['ParseSignatureParams'](arg1);
}

export function ValidateBareColumnRefs(arg1) {
  return window['go']['sqleditor']['Service']['ValidateBareColumnRefs'](arg1);
}

export function ValidateDataTypes(arg1, arg2) {
  return window['go']['sqleditor']['Service']['ValidateDataTypes'](arg1, arg2);
}

export function ValidateSnowflakePatterns(arg1, arg2) {
  return window['go']['sqleditor']['Service']['ValidateSnowflakePatterns'](arg1, arg2);
}

export function ValidateTablesExist(arg1) {
  return window['go']['sqleditor']['Service']['ValidateTablesExist'](arg1);
}
