# ─── Docs generation ──────────────────────────────────────────────────────────
#
# make docs          Regenerate all documentation (frontend + backend).
# make docs-serve    Serve docs/ locally at http://localhost:4000
# make install-tools Install gomarkdoc (run once). TypeDoc runs via npx (see frontend/package.json).

GOPATH_BIN   := $(shell go env GOPATH)/bin
GOMARKDOC    := $(GOPATH_BIN)/gomarkdoc

DOCS_DIR     := docs
DOCS_BACKEND := $(DOCS_DIR)/backend
DOCS_FRONTEND:= $(DOCS_DIR)/frontend
DOCS_PORT    := 4000

# Internal Go packages to document (integration is test-only, excluded).
GO_INTERNAL_PACKAGES := \
	./internal/ai \
	./internal/config \
	./internal/crashreport \
	./internal/ddl \
	./internal/filesystem \
	./internal/gitrepo \
	./internal/logger \
	./internal/sfconfig \
	./internal/snowflake \
	./internal/telemetry

.PHONY: docs docs-frontend docs-backend docs-sidebar docs-serve install-tools

## docs: Regenerate all documentation (frontend + backend + sidebar).
docs: docs-frontend docs-backend docs-sidebar
	@echo ""
	@echo "Docs written to $(DOCS_DIR)/."
	@echo "Run 'make docs-serve' to view at http://localhost:$(DOCS_PORT)"

## docs-frontend: Generate TypeScript/React docs with TypeDoc → docs/frontend/
docs-frontend:
	@echo "==> Frontend docs (TypeDoc)…"
	@mkdir -p $(DOCS_FRONTEND)
	cd frontend && npm run docs

## docs-backend: Generate Go docs with gomarkdoc → docs/backend/
docs-backend:
	@echo "==> Backend docs (gomarkdoc)…"
	@mkdir -p $(DOCS_BACKEND)/internal
	$(GOMARKDOC) --output "$(DOCS_BACKEND)/app.md" .
	$(GOMARKDOC) --output "$(DOCS_BACKEND)/{{.Dir}}.md" $(GO_INTERNAL_PACKAGES)

## docs-sidebar: Regenerate docs/_sidebar.md from the generated file tree.
docs-sidebar:
	@echo "==> Regenerating sidebar…"
	@{ \
		echo '<!-- AUTO-GENERATED by make docs — do not edit by hand -->'; \
		echo ''; \
		echo '- [Home](/)'; \
		echo ''; \
		echo '- **Concepts** (hand-written)'; \
		echo '  - [Overview](concepts/README.md)'; \
		for f in $(DOCS_DIR)/concepts/*.md; do \
			name=$$(basename "$$f" .md); \
			[ "$$name" = "README" ] && continue; \
			echo "  - [$$name](concepts/$$name.md)"; \
		done; \
		echo ''; \
		echo '- **Backend (Go)**'; \
		echo '  - [App](backend/app.md)'; \
		for f in $(DOCS_BACKEND)/internal/*.md; do \
			pkg=$$(basename "$$f" .md); \
			echo "  - [internal/$$pkg](backend/internal/$$pkg.md)"; \
		done; \
		echo ''; \
		echo '- **Frontend (TypeScript)**'; \
		echo '  - [Module index](frontend/README.md)'; \
		echo '  - [App](frontend/App.md)'; \
		echo '  - [main](frontend/main.md)'; \
		echo '  - **Stores**'; \
		for f in $(DOCS_FRONTEND)/store/*.md; do \
			name=$$(basename "$$f" .md); \
			echo "    - [$$name](frontend/store/$$name.md)"; \
		done; \
		echo '  - **Pages**'; \
		for f in $(DOCS_FRONTEND)/pages/*.md; do \
			name=$$(basename "$$f" .md); \
			echo "    - [$$name](frontend/pages/$$name.md)"; \
		done; \
		for dir in $(DOCS_FRONTEND)/components/*/; do \
			category=$$(basename "$$dir"); \
			echo "  - **Components — $$category**"; \
			for f in "$$dir"*.md; do \
				[ -f "$$f" ] || continue; \
				name=$$(basename "$$f" .md); \
				echo "    - [$$name](frontend/components/$$category/$$name.md)"; \
			done; \
		done; \
	} > $(DOCS_DIR)/_sidebar.md

## docs-serve: Serve docs/ locally at http://localhost:$(DOCS_PORT)
docs-serve:
	@echo "Serving docs at http://localhost:$(DOCS_PORT) — Ctrl+C to stop"
	python3 -m http.server $(DOCS_PORT) --directory $(DOCS_DIR)

## install-tools: Install gomarkdoc (run once per machine). TypeDoc needs no install:
## `npm run docs` fetches it via npx with its own TypeScript 5.x (TypeDoc can't run on TS 7).
install-tools:
	@echo "==> Installing gomarkdoc…"
	go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
	@echo "Done. You can now run 'make docs'."
