// Code generated by scripts/gen_semantic_map.go; DO NOT EDIT.
// Regenerate with: go generate ./internal/architecture/

package architecture

// GetCodebaseSemanticMap is a marker function exclusively for LLM workflow context.
// It returns a JSON-formatted string defining the domain boundaries of the Thaw app.
// ALL LLM agents MUST read this map before proposing architectural changes or new features.
func GetCodebaseSemanticMap() string {
	return `{
  "domains": [
    {
      "name": "Core IPC \u0026 App Lifecycle",
      "backend_paths": [
        "app.go",
        "internal/apperrors/",
        "internal/config/",
        "internal/crashreport/",
        "internal/filesystem/",
        "internal/logger/",
        "internal/session/",
        "internal/sfconfig/",
        "internal/telemetry/",
        "internal/version/",
        "main.go"
      ],
      "frontend_paths": [
        "frontend/src/components/connection/ConnectModal.tsx",
        "frontend/src/components/settings/SessionManagementModal.tsx",
        "frontend/src/components/toolbar/Toolbar.tsx",
        "frontend/src/store/connectionStore.ts",
        "frontend/wailsjs/"
      ],
      "description": "Wails entry points, window state persistence, and Zustand state management."
    },
    {
      "name": "SQL Editor \u0026 Diagnostics",
      "backend_paths": [
        "internal/queryprofile/",
        "internal/sqleditor/"
      ],
      "frontend_paths": [
        "frontend/src/components/editor/SqlEditor.tsx",
        "frontend/src/components/editor/sqlEditorUtils.ts",
        "frontend/src/components/results/ColumnFilterDropdown.tsx",
        "frontend/src/components/results/ConditionalFormattingModal.tsx",
        "frontend/src/components/results/DataTypeFormatModal.tsx",
        "frontend/src/components/results/GridSearch.tsx",
        "frontend/src/components/results/QuickChartModal.tsx",
        "frontend/src/components/results/ResultGrid.tsx",
        "frontend/src/components/results/StatusBar.tsx",
        "frontend/src/store/gridStore.ts",
        "frontend/src/store/queryStore.ts"
      ],
      "description": "Proprietary SQL tokenizer, syntax validation, and Monaco editor UI components."
    },
    {
      "name": "Object Browser \u0026 Administration",
      "backend_paths": [
        "internal/fnmeta/",
        "internal/integrations/",
        "internal/pipe/",
        "internal/procedure/",
        "internal/secret/",
        "internal/snowflake/",
        "internal/stage/",
        "internal/tasks/"
      ],
      "frontend_paths": [
        "frontend/src/components/account/AccountPanel.tsx",
        "frontend/src/components/database/CreateStageModal.tsx",
        "frontend/src/components/database/StagePropertiesModal.tsx",
        "frontend/src/components/layout/Sidebar.tsx",
        "frontend/src/components/task/TaskHistoryModal.tsx",
        "frontend/src/store/objectStore.ts"
      ],
      "description": "Database metadata exploration, user management, and warehouse metering."
    },
    {
      "name": "Schema Migration",
      "backend_paths": [
        "internal/ddl/",
        "internal/fileformat/",
        "internal/migration/"
      ],
      "frontend_paths": [
        "frontend/src/components/migration/ExecGrid.tsx",
        "frontend/src/components/migration/MigrationModal.tsx",
        "frontend/src/components/migration/ReviewGrid.tsx",
        "frontend/src/components/migration/migrationUtils.ts",
        "frontend/src/store/diffStore.ts"
      ],
      "description": "DDL extraction, schema diffing, and the deployment wizard."
    },
    {
      "name": "AI Tooling",
      "backend_paths": [
        "internal/ai/"
      ],
      "frontend_paths": [
        "frontend/src/components/chat/AiChat.tsx"
      ],
      "description": "API clients for LLM providers and agentic tool-calling execution loops."
    },
    {
      "name": "Snowpark \u0026 Developer Workflows",
      "backend_paths": [
        "internal/dbt/",
        "internal/snowpark/"
      ],
      "frontend_paths": [
        "frontend/src/components/notebook/NotebookTab.tsx",
        "frontend/src/components/toolbar/NotebookToolbarSlot.tsx",
        "frontend/src/store/notebookPrefsStore.ts",
        "frontend/src/store/notebookToolbarStore.ts"
      ],
      "description": "Python environment management, Jupyter kernels, and dbt project scaffolding."
    },
    {
      "name": "Git Integration",
      "backend_paths": [
        "internal/gitrepo/",
        "internal/snowgitrepo/"
      ],
      "frontend_paths": [
        "frontend/src/components/git/GitOperationsDialog.tsx",
        "frontend/src/store/gitStore.ts"
      ],
      "description": "Git repository operations, Snowflake Git repository objects, and schema export versioning."
    }
  ]
}`
}
