// Code generated by scripts/gen_semantic_map.go; DO NOT EDIT.
// Regenerate with: go generate ./internal/architecture/

package architecture

// GetCodebaseSemanticMap is a marker function exclusively for LLM workflow context.
// It returns a JSON-formatted string defining the domain boundaries of the Thaw app.
// ALL LLM agents MUST read this map before proposing architectural changes or new features.
func GetCodebaseSemanticMap() string {
	return `{
  "domains": [
    {
      "name": "Core IPC \u0026 App Lifecycle",
      "backend_paths": [
        "internal/app/",
        "internal/apperrors/",
        "internal/config/",
        "internal/crashreport/",
        "internal/filesystem/",
        "internal/logger/",
        "internal/session/",
        "internal/sfconfig/",
        "internal/sysinfo/",
        "internal/telemetry/",
        "internal/version/",
        "main.go"
      ],
      "frontend_paths": [
        "frontend/src/components/connection/ConnectModal.tsx",
        "frontend/src/components/settings/SessionManagementModal.tsx",
        "frontend/src/components/toolbar/Toolbar.tsx",
        "frontend/src/store/connectionStore.ts",
        "frontend/wailsjs/"
      ],
      "description": "Wails entry points, window state persistence, and Zustand state management."
    },
    {
      "name": "SQL Editor \u0026 Diagnostics",
      "backend_paths": [
        "internal/queryhistory/",
        "internal/querylog/",
        "internal/queryprofile/",
        "internal/sqleditor/",
        "internal/sqltok/"
      ],
      "frontend_paths": [
        "frontend/src/components/editor/CrossTabSearch.tsx",
        "frontend/src/components/editor/SqlEditor.tsx",
        "frontend/src/components/editor/sqlEditorUtils.ts",
        "frontend/src/components/results/CellDetailPanel.tsx",
        "frontend/src/components/results/ColumnFilterDropdown.tsx",
        "frontend/src/components/results/ConditionalFormattingModal.tsx",
        "frontend/src/components/results/DataTypeFormatModal.tsx",
        "frontend/src/components/results/GridSearch.tsx",
        "frontend/src/components/results/QueryLogPane.tsx",
        "frontend/src/components/results/QuickChartModal.tsx",
        "frontend/src/components/results/ResultGrid.tsx",
        "frontend/src/components/results/StatusBar.tsx",
        "frontend/src/components/results/cellDetailUtils.ts",
        "frontend/src/components/results/columnOrderUtils.ts",
        "frontend/src/store/gridStore.ts",
        "frontend/src/store/queryStore.ts"
      ],
      "description": "Proprietary SQL tokenizer, syntax validation, and Monaco editor UI components."
    },
    {
      "name": "Object Browser \u0026 Administration",
      "backend_paths": [
        "internal/alert/",
        "internal/backup/",
        "internal/column/",
        "internal/dbtproject/",
        "internal/dynamictable/",
        "internal/externaltable/",
        "internal/fnmeta/",
        "internal/integrations/",
        "internal/keypair/",
        "internal/maskingpolicy/",
        "internal/materializedview/",
        "internal/networkrule/",
        "internal/objects/",
        "internal/pipe/",
        "internal/procedure/",
        "internal/secret/",
        "internal/snowflake/",
        "internal/sqlutil/",
        "internal/stage/",
        "internal/table/",
        "internal/tag/",
        "internal/tasks/",
        "internal/warehouse/"
      ],
      "frontend_paths": [
        "frontend/src/components/account/AccountPanel.tsx",
        "frontend/src/components/alert/AlertPropertiesModal.tsx",
        "frontend/src/components/alert/CreateAlertModal.tsx",
        "frontend/src/components/database/CreateStageModal.tsx",
        "frontend/src/components/database/StagePropertiesModal.tsx",
        "frontend/src/components/dbtproject/AddDbtProjectVersionModal.tsx",
        "frontend/src/components/dbtproject/CreateDbtProjectModal.tsx",
        "frontend/src/components/dbtproject/ExecuteDbtProjectModal.tsx",
        "frontend/src/components/dbtproject/ModifyDbtProjectModal.tsx",
        "frontend/src/components/dbtproject/SourceLocationPicker.tsx",
        "frontend/src/components/dynamictable/CreateDynamicTableModal.tsx",
        "frontend/src/components/dynamictable/DynamicTablePropertiesModal.tsx",
        "frontend/src/components/externaltable/CreateExternalTableModal.tsx",
        "frontend/src/components/externaltable/ExternalTablePropertiesModal.tsx",
        "frontend/src/components/layout/Sidebar.tsx",
        "frontend/src/components/maskingpolicy/CreateMaskingPolicyModal.tsx",
        "frontend/src/components/maskingpolicy/MaskingPolicyPropertiesModal.tsx",
        "frontend/src/components/materializedview/CreateMaterializedViewModal.tsx",
        "frontend/src/components/materializedview/MaterializedViewPropertiesModal.tsx",
        "frontend/src/components/networkrule/CreateNetworkRuleModal.tsx",
        "frontend/src/components/networkrule/NetworkRulePropertiesModal.tsx",
        "frontend/src/components/networkrule/valueList.ts",
        "frontend/src/components/shared/CreateModalShell.tsx",
        "frontend/src/components/shared/MonacoSqlField.tsx",
        "frontend/src/components/shared/NameWithReplaceOptions.tsx",
        "frontend/src/components/shared/SqlPreview.tsx",
        "frontend/src/components/shared/TagInput.tsx",
        "frontend/src/components/shared/createModalHooks.ts",
        "frontend/src/components/sidebar/objectIcons.tsx",
        "frontend/src/components/tag/CreateTagModal.tsx",
        "frontend/src/components/tag/TagPropertiesModal.tsx",
        "frontend/src/components/task/TaskHistoryModal.tsx",
        "frontend/src/store/objectStore.ts"
      ],
      "description": "Database metadata exploration, user management, and warehouse metering."
    },
    {
      "name": "Schema Migration",
      "backend_paths": [
        "internal/ddl/",
        "internal/fileformat/",
        "internal/migration/"
      ],
      "frontend_paths": [
        "frontend/src/components/migration/ExecGrid.tsx",
        "frontend/src/components/migration/MigrationModal.tsx",
        "frontend/src/components/migration/ReviewGrid.tsx",
        "frontend/src/components/migration/migrationUtils.ts",
        "frontend/src/store/diffStore.ts"
      ],
      "description": "DDL extraction, schema diffing, and the deployment wizard."
    },
    {
      "name": "AI Tooling",
      "backend_paths": [
        "internal/ai/"
      ],
      "frontend_paths": null,
      "description": "API clients for LLM providers; inline completion and model management."
    },
    {
      "name": "Snowpark \u0026 Developer Workflows",
      "backend_paths": [
        "internal/dbt/",
        "internal/snowpark/"
      ],
      "frontend_paths": [
        "frontend/src/components/notebook/NotebookTab.tsx",
        "frontend/src/components/notebook/NotebookToolbarSlot.tsx",
        "frontend/src/store/notebookPrefsStore.ts",
        "frontend/src/store/notebookToolbarStore.ts"
      ],
      "description": "Python environment management, Jupyter kernels, and dbt project scaffolding."
    },
    {
      "name": "Git Integration",
      "backend_paths": [
        "internal/gitrepo/",
        "internal/snowgitrepo/"
      ],
      "frontend_paths": [
        "frontend/src/components/git/GitOperationsDialog.tsx",
        "frontend/src/store/gitStore.ts"
      ],
      "description": "Git repository operations, Snowflake Git repository objects, and schema export versioning."
    },
    {
      "name": "MCP Server",
      "backend_paths": [
        "internal/mcp/"
      ],
      "frontend_paths": [
        "frontend/src/components/settings/MCPSessionsModal.tsx",
        "frontend/src/components/toolbar/MCPIndicator.tsx",
        "frontend/src/hooks/useEditorContextSync.ts",
        "frontend/src/store/mcpStore.ts"
      ],
      "description": "Model Context Protocol servers exposing the Snowflake connection to external AI clients over localhost."
    },
    {
      "name": "ER Designer",
      "backend_paths": [
        "internal/erdesigner/"
      ],
      "frontend_paths": [
        "frontend/src/components/er/ERCanvas.tsx",
        "frontend/src/components/er/ERDesigner.tsx",
        "frontend/src/components/er/ERDiagramModal.tsx",
        "frontend/src/components/er/ERTableNode.tsx",
        "frontend/src/components/er/JoinQueryPanel.tsx",
        "frontend/src/components/er/buildMermaid.ts",
        "frontend/src/components/er/erCanvasLayout.ts",
        "frontend/src/components/er/erLayoutStore.ts",
        "frontend/src/components/er/erTypes.ts"
      ],
      "description": "Entity-relationship diagram viewer, interactive table designer, join pathfinding, and SQL generation."
    }
  ]
}`
}
