// Copyright (c) 2026 Technarion Oy. All rights reserved.
//
// This software and its source code are proprietary and confidential.
// Unauthorized copying, distribution, modification, or use of this software,
// in whole or in part, is strictly prohibited without prior written permission
// from Technarion Oy.

package sqleditor

import (
	"strings"
	"testing"
)

// accountAdminDDL is a real-world ACCOUNTADMIN role DDL export from a live
// Snowflake account, used to cross-validate the GRANT statement validator.
const accountAdminDDL = `CREATE ROLE IF NOT EXISTS "ACCOUNTADMIN"
  COMMENT = 'Account administrator can manage all aspects of the account.';
GRANT APPLY BACKUP RETENTION LOCK ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT APPLY CONTACT ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT APPLY LEGAL HOLD ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT APPLY RESOURCE GROUP ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT APPLY STORAGE LIFECYCLE POLICY ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT APPLY TAG ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT AUDIT ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CANCEL QUERY ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE ACCOUNT ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE API INTEGRATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE APPLICATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE EXTERNAL ACCESS INTEGRATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE EXTERNAL VOLUME ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE FAILOVER GROUP ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE LISTING ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE MIGRATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE OPENFLOW DATA PLANE INTEGRATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE OPENFLOW RUNTIME INTEGRATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE ORGANIZATION LISTING ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE POSTGRES INSTANCE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE PREVIEW APPLICATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE PROVISIONED THROUGHPUT ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE REPLICATION GROUP ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE SECURITY INTEGRATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE SHARE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE SNOWFLAKE INTELLIGENCE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT CREATE UPSTREAM REPOSITORY ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT DELETE LINEAGE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT EXECUTE ALERT ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT EXECUTE AUTO CLASSIFICATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT EXECUTE MANAGED ALERT ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT EXECUTE SPARK APPLICATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT IMPORT ORGANIZATION LISTING ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT IMPORT ORGANIZATION USER GROUPS ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT INGEST LINEAGE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE ACCOUNT SUPPORT CASES ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE BILLING ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE DATA QUALITY ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE EVENT SHARING ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE FIREWALL_CONFIGURATION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE POSTGRES PRIVATE CONNECTIVITY ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE SHARE TARGET ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE USER SUPPORT CASES ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MANAGE WAREHOUSES ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY LOG EVENT LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY LOG LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY METRIC LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY SESSION LOG EVENT LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY SESSION LOG LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY SESSION METRIC LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY SESSION TRACE LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MODIFY TRACE LEVEL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MONITOR ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MONITOR ROLE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MONITOR SECURITY ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT MONITOR USER ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT OVERRIDE SHARE RESTRICTIONS ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT PURCHASE DATA EXCHANGE LISTING ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT READ SESSION ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT READ UNREDACTED AI OBSERVABILITY EVENTS TABLE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT READ UNREDACTED ERROR TABLE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT REPLICATE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT RESOLVE ALL ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT USE AI FUNCTIONS ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT VIEW LINEAGE ON ACCOUNT TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT USAGE ON APPLICATION_ROLE SNOWFLAKE.DATA_QUALITY_MONITORING_LOOKUP TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT USAGE ON APPLICATION_ROLE SNOWFLAKE.PERFORMANCE_EXPLORER_PUBLIC_USER TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT USAGE ON APPLICATION_ROLE SNOWFLAKE.PUBLIC TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT INSTANTIATE ON CLASS SNOWFLAKE.CORE.BUDGET TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON CLASS SNOWFLAKE.CORE.BUDGET TO ROLE "ACCOUNTADMIN";
GRANT INSTANTIATE ON CLASS SNOWFLAKE.CORE.QUOTA TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON CLASS SNOWFLAKE.CORE.QUOTA TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON CLASS SNOWFLAKE.MARKETPLACE_NOTIFICATION.MARKETPLACE_ANALYTICS_NOTIFICATION TO ROLE "ACCOUNTADMIN";
GRANT INSTANTIATE ON CLASS SNOWFLAKE.ML.DOCUMENT_INTELLIGENCE TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON CLASS SNOWFLAKE.ML.DOCUMENT_INTELLIGENCE TO ROLE "ACCOUNTADMIN";
GRANT INSTANTIATE ON CLASS SNOWFLAKE.WORKLOAD_INSIGHTS.ANOMALY_INSIGHTS TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON CLASS SNOWFLAKE.WORKLOAD_INSIGHTS.ANOMALY_INSIGHTS TO ROLE "ACCOUNTADMIN";
GRANT INSTANTIATE ON CLASS SNOWFLAKE.WORKLOAD_INSIGHTS.COST_INSIGHTS TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON CLASS SNOWFLAKE.WORKLOAD_INSIGHTS.COST_INSIGHTS TO ROLE "ACCOUNTADMIN";
GRANT INSTANTIATE ON CLASS SNOWFLAKE.WORKLOAD_OPTIMIZATION.PERFORMANCE_EXPLORER TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON CLASS SNOWFLAKE.WORKLOAD_OPTIMIZATION.PERFORMANCE_EXPLORER TO ROLE "ACCOUNTADMIN";
GRANT OWNERSHIP ON COMPUTE_POOL SYSTEM_COMPUTE_POOL_CPU TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT OWNERSHIP ON COMPUTE_POOL SYSTEM_COMPUTE_POOL_GPU TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT REFERENCE_USAGE ON DATABASE SNOWFLAKE TO ROLE "ACCOUNTADMIN";
GRANT OWNERSHIP ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT OWNERSHIP ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT USAGE ON DATABASE_ROLE SNOWFLAKE.AI_FUNCTIONS_USER TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON DATABASE_ROLE SNOWFLAKE.ALERT_VIEWER TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON FUNCTION SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES_WITH_LINEAGE(VARCHAR) TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON FUNCTION SNOWFLAKE.CORE.DATA_METRIC_SCHEDULED_TIME() TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON FUNCTION SNOWFLAKE.ML.TOP_INSIGHTS(OBJECT, OBJECT, FLOAT, BOOLEAN) TO ROLE "ACCOUNTADMIN";
GRANT READ ON IMAGE_REPOSITORY SNOWHOUSE_IMPORT.IMAGES.EXTERNAL_IMAGES TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON PROCEDURE SNOWFLAKE.ALERT.CREATE_RECOMMENDED_ALERTS(OBJECT) TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON PROCEDURE SNOWFLAKE.CORTEX.CREATE_AI_FUNCTION(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARIANT, VARIANT, VARCHAR, VARCHAR, VARCHAR) TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON PROCEDURE SNOWFLAKE.DATA_PRIVACY.RESET_PRIVACY_BUDGET(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE "ACCOUNTADMIN";
GRANT OWNERSHIP ON ROLE GITHUB_CI_TEST_ROLE TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT ROLE SECURITYADMIN TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON SCHEMA SNOWFLAKE.ACCOUNT_USAGE TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON SCHEMA SNOWFLAKE.ALERT TO ROLE "ACCOUNTADMIN";
GRANT SELECT ON TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF001.CUSTOMER TO ROLE "ACCOUNTADMIN";
GRANT SELECT ON TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF001.LINEITEM TO ROLE "ACCOUNTADMIN";
GRANT APPLY ON TAG SNOWFLAKE.CORE.CERTIFICATION_STATUS TO ROLE "ACCOUNTADMIN";
GRANT OWNERSHIP ON USER KALLESIUKOLA TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT SELECT ON VIEW SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY TO ROLE "ACCOUNTADMIN";
GRANT SELECT ON VIEW SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY TO ROLE "ACCOUNTADMIN";
GRANT OWNERSHIP ON WAREHOUSE COMPUTE_WH TO ROLE "ACCOUNTADMIN" WITH GRANT OPTION;
GRANT ROLE "ACCOUNTADMIN" TO USER "KALLESIUKOLA";`

// TestAccountAdminDDL_CrossValidation feeds every statement from a real
// ACCOUNTADMIN role DDL export through ValidateSnowflakePatterns to identify
// which statements the validator considers invalid. This surfaces gaps in
// the grantObjectPrivileges map and the _grantObjType regex.
func TestAccountAdminDDL_CrossValidation(t *testing.T) {
	stmts := splitDDLStatements(accountAdminDDL)
	if len(stmts) == 0 {
		t.Fatal("no statements parsed from accountAdminDDL")
	}

	var failures []string
	for _, stmt := range stmts {
		ranges := GetStatementRanges(stmt)
		markers := ValidateSnowflakePatterns(stmt, ranges)
		warnings := getWarnings(markers)
		if len(warnings) > 0 {
			var msgs []string
			for _, w := range warnings {
				msgs = append(msgs, w.Message)
			}
			failures = append(failures, stmt+" → "+strings.Join(msgs, "; "))
		}
	}

	if len(failures) > 0 {
		t.Errorf("Validator flagged %d/%d statements as invalid:\n\n%s",
			len(failures), len(stmts), strings.Join(failures, "\n\n"))
	}
}

// splitDDLStatements splits a multi-statement DDL string on semicolons,
// trimming whitespace and skipping empty entries.
func splitDDLStatements(ddl string) []string {
	raw := strings.Split(ddl, ";")
	var result []string
	for _, s := range raw {
		s = strings.TrimSpace(s)
		if s != "" {
			result = append(result, s)
		}
	}
	return result
}
