// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackup(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddBackup'](arg1, arg2, arg3);
}

export function AlterBackupPolicy(arg1, arg2) {
  return window['go']['app']['App']['AlterBackupPolicy'](arg1, arg2);
}

export function AlterBackupSet(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterBackupSet'](arg1, arg2, arg3, arg4);
}

export function AlterPipe(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterPipe'](arg1, arg2, arg3, arg4);
}

export function AlterStage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterStage'](arg1, arg2, arg3, arg4);
}

export function AlterTableProperty(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AlterTableProperty'](arg1, arg2, arg3, arg4, arg5);
}

export function AlterTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterTask'](arg1, arg2, arg3, arg4);
}

export function AlterWarehouseAbortAllQueries(arg1) {
  return window['go']['app']['App']['AlterWarehouseAbortAllQueries'](arg1);
}

export function AlterWarehouseProperty(arg1, arg2, arg3) {
  return window['go']['app']['App']['AlterWarehouseProperty'](arg1, arg2, arg3);
}

export function AlterWarehouseRename(arg1, arg2) {
  return window['go']['app']['App']['AlterWarehouseRename'](arg1, arg2);
}

export function AlterWarehouseResume(arg1) {
  return window['go']['app']['App']['AlterWarehouseResume'](arg1);
}

export function AlterWarehouseSuspend(arg1) {
  return window['go']['app']['App']['AlterWarehouseSuspend'](arg1);
}

export function AnalyzeMigration(arg1, arg2) {
  return window['go']['app']['App']['AnalyzeMigration'](arg1, arg2);
}

export function BuildAddColumnSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildAddColumnSql'](arg1, arg2, arg3, arg4);
}

export function BuildAddDbtProjectVersionSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildAddDbtProjectVersionSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildAlterDbtProjectSetSql(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['BuildAlterDbtProjectSetSql'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function BuildAlterStageSql(arg1) {
  return window['go']['app']['App']['BuildAlterStageSql'](arg1);
}

export function BuildApiIntegrationPreviewSQL(arg1) {
  return window['go']['app']['App']['BuildApiIntegrationPreviewSQL'](arg1);
}

export function BuildCallStatement(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildCallStatement'](arg1, arg2, arg3, arg4);
}

export function BuildChangeColumnTypeSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildChangeColumnTypeSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildCreateDbtProjectSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateDbtProjectSql'](arg1, arg2, arg3);
}

export function BuildCreateFileFormatSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateFileFormatSql'](arg1, arg2, arg3);
}

export function BuildCreateGitRepositorySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateGitRepositorySql'](arg1, arg2, arg3);
}

export function BuildCreatePipeSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreatePipeSql'](arg1, arg2, arg3);
}

export function BuildCreateSecretSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateSecretSql'](arg1, arg2, arg3);
}

export function BuildCreateStageSql(arg1) {
  return window['go']['app']['App']['BuildCreateStageSql'](arg1);
}

export function BuildDropColumnNotNullSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildDropColumnNotNullSql'](arg1, arg2, arg3, arg4);
}

export function BuildDropColumnSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildDropColumnSql'](arg1, arg2, arg3, arg4);
}

export function BuildExecuteDbtProjectSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildExecuteDbtProjectSql'](arg1, arg2, arg3, arg4);
}

export function BuildFunctionSelectStatement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildFunctionSelectStatement'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildModifyGitRepositorySql(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['BuildModifyGitRepositorySql'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BuildModifySecretSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildModifySecretSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildRefreshPipeSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildRefreshPipeSql'](arg1, arg2, arg3, arg4);
}

export function BuildRenameColumnSql(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['BuildRenameColumnSql'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BuildSetColumnCommentSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildSetColumnCommentSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildSetColumnNotNullSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildSetColumnNotNullSql'](arg1, arg2, arg3, arg4);
}

export function CanCreateIntegration(arg1) {
  return window['go']['app']['App']['CanCreateIntegration'](arg1);
}

export function CanCreateUsers(arg1) {
  return window['go']['app']['App']['CanCreateUsers'](arg1);
}

export function CanManageUsers(arg1) {
  return window['go']['app']['App']['CanManageUsers'](arg1);
}

export function CanModifyUserAuth(arg1) {
  return window['go']['app']['App']['CanModifyUserAuth'](arg1);
}

export function CanViewWarehouseMeteringHistory() {
  return window['go']['app']['App']['CanViewWarehouseMeteringHistory']();
}

export function CancelConnect() {
  return window['go']['app']['App']['CancelConnect']();
}

export function CancelExport() {
  return window['go']['app']['App']['CancelExport']();
}

export function CancelMigration() {
  return window['go']['app']['App']['CancelMigration']();
}

export function CancelQuery(arg1) {
  return window['go']['app']['App']['CancelQuery'](arg1);
}

export function CheckAvailableKeyTools() {
  return window['go']['app']['App']['CheckAvailableKeyTools']();
}

export function CheckPythonSyntax(arg1, arg2, arg3) {
  return window['go']['app']['App']['CheckPythonSyntax'](arg1, arg2, arg3);
}

export function CheckSnowparkEnv() {
  return window['go']['app']['App']['CheckSnowparkEnv']();
}

export function ClearDefaultProfile() {
  return window['go']['app']['App']['ClearDefaultProfile']();
}

export function ClearObjectCache() {
  return window['go']['app']['App']['ClearObjectCache']();
}

export function ClearObjectCacheForDatabase(arg1) {
  return window['go']['app']['App']['ClearObjectCacheForDatabase'](arg1);
}

export function CloneChildTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CloneChildTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CloneProfile(arg1, arg2) {
  return window['go']['app']['App']['CloneProfile'](arg1, arg2);
}

export function CloseTabSession(arg1) {
  return window['go']['app']['App']['CloseTabSession'](arg1);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function CreateApiIntegration(arg1) {
  return window['go']['app']['App']['CreateApiIntegration'](arg1);
}

export function CreateBackupPolicy(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['CreateBackupPolicy'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateBackupSet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['CreateBackupSet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateCatalogIntegration(arg1) {
  return window['go']['app']['App']['CreateCatalogIntegration'](arg1);
}

export function CreateDbtProject(arg1, arg2) {
  return window['go']['app']['App']['CreateDbtProject'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['app']['App']['CreateDirectory'](arg1);
}

export function CreateExternalAccessIntegration(arg1) {
  return window['go']['app']['App']['CreateExternalAccessIntegration'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['app']['App']['CreateFile'](arg1);
}

export function CreateMigrationSnapshot(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['CreateMigrationSnapshot'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateNotificationIntegration(arg1) {
  return window['go']['app']['App']['CreateNotificationIntegration'](arg1);
}

export function CreateSecurityIntegration(arg1) {
  return window['go']['app']['App']['CreateSecurityIntegration'](arg1);
}

export function CreateStorageIntegration(arg1) {
  return window['go']['app']['App']['CreateStorageIntegration'](arg1);
}

export function DebugNotebookCell(arg1, arg2, arg3) {
  return window['go']['app']['App']['DebugNotebookCell'](arg1, arg2, arg3);
}

export function DeleteDirectory(arg1) {
  return window['go']['app']['App']['DeleteDirectory'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteOldestBackup(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteOldestBackup'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DeleteVenvFolder() {
  return window['go']['app']['App']['DeleteVenvFolder']();
}

export function DeployNotebook(arg1) {
  return window['go']['app']['App']['DeployNotebook'](arg1);
}

export function DescribeDbtProject(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeDbtProject'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function DownloadFileFromStage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DownloadFileFromStage'](arg1, arg2, arg3, arg4);
}

export function DropBackupPolicy(arg1) {
  return window['go']['app']['App']['DropBackupPolicy'](arg1);
}

export function DropBackupSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropBackupSet'](arg1, arg2, arg3);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['app']['App']['DropDatabase'](arg1, arg2);
}

export function DropIntegration(arg1) {
  return window['go']['app']['App']['DropIntegration'](arg1);
}

export function DropSchema(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropSchema'](arg1, arg2, arg3);
}

export function DropTaskTree(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropTaskTree'](arg1, arg2, arg3);
}

export function DuplicateFile(arg1) {
  return window['go']['app']['App']['DuplicateFile'](arg1);
}

export function EnableTaskDependents(arg1, arg2, arg3) {
  return window['go']['app']['App']['EnableTaskDependents'](arg1, arg2, arg3);
}

export function ExecDDL(arg1) {
  return window['go']['app']['App']['ExecDDL'](arg1);
}

export function ExecuteGitFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteGitFile'](arg1, arg2, arg3, arg4);
}

export function ExecuteMigration(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteMigration'](arg1, arg2, arg3, arg4);
}

export function ExecuteNotebook(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteNotebook'](arg1, arg2, arg3, arg4);
}

export function ExecuteQuery(arg1) {
  return window['go']['app']['App']['ExecuteQuery'](arg1);
}

export function ExecuteStageFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteStageFile'](arg1, arg2, arg3, arg4);
}

export function ExecuteTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ExecuteTask'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportAccountObjectsDDL(arg1) {
  return window['go']['app']['App']['ExportAccountObjectsDDL'](arg1);
}

export function ExportAllDatabasesDDL(arg1, arg2) {
  return window['go']['app']['App']['ExportAllDatabasesDDL'](arg1, arg2);
}

export function ExportDatabaseDDL(arg1, arg2) {
  return window['go']['app']['App']['ExportDatabaseDDL'](arg1, arg2);
}

export function ExportGraphDDL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportGraphDDL'](arg1, arg2, arg3, arg4);
}

export function ExportTableData(arg1) {
  return window['go']['app']['App']['ExportTableData'](arg1);
}

export function FetchNotebookContent(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchNotebookContent'](arg1, arg2, arg3);
}

export function GenerateKeyPair(arg1, arg2, arg3) {
  return window['go']['app']['App']['GenerateKeyPair'](arg1, arg2, arg3);
}

export function GenerateMigrationScript(arg1, arg2, arg3) {
  return window['go']['app']['App']['GenerateMigrationScript'](arg1, arg2, arg3);
}

export function GetAIConfig() {
  return window['go']['app']['App']['GetAIConfig']();
}

export function GetAISuggestion(arg1) {
  return window['go']['app']['App']['GetAISuggestion'](arg1);
}

export function GetAdminLockedFlags() {
  return window['go']['app']['App']['GetAdminLockedFlags']();
}

export function GetAllDataTypes() {
  return window['go']['app']['App']['GetAllDataTypes']();
}

export function GetAllFunctionNames() {
  return window['go']['app']['App']['GetAllFunctionNames']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAvailableShells() {
  return window['go']['app']['App']['GetAvailableShells']();
}

export function GetCollationLocales() {
  return window['go']['app']['App']['GetCollationLocales']();
}

export function GetCollationSpecifiers() {
  return window['go']['app']['App']['GetCollationSpecifiers']();
}

export function GetCollations() {
  return window['go']['app']['App']['GetCollations']();
}

export function GetColumnComments(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetColumnComments'](arg1, arg2, arg3);
}

export function GetCurrentRegion() {
  return window['go']['app']['App']['GetCurrentRegion']();
}

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetDatabaseCrossDeps(arg1, arg2) {
  return window['go']['app']['App']['GetDatabaseCrossDeps'](arg1, arg2);
}

export function GetDatabaseRetentionDays(arg1) {
  return window['go']['app']['App']['GetDatabaseRetentionDays'](arg1);
}

export function GetDatabaseTableSummary(arg1) {
  return window['go']['app']['App']['GetDatabaseTableSummary'](arg1);
}

export function GetDefaultSessionConfig() {
  return window['go']['app']['App']['GetDefaultSessionConfig']();
}

export function GetERDiagramData(arg1) {
  return window['go']['app']['App']['GetERDiagramData'](arg1);
}

export function GetEditorPrefs() {
  return window['go']['app']['App']['GetEditorPrefs']();
}

export function GetFeatureFlags() {
  return window['go']['app']['App']['GetFeatureFlags']();
}

export function GetFunctionInfo(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetFunctionInfo'](arg1, arg2, arg3, arg4);
}

export function GetFunctionSuggestions(arg1) {
  return window['go']['app']['App']['GetFunctionSuggestions'](arg1);
}

export function GetFunctionTooltip(arg1) {
  return window['go']['app']['App']['GetFunctionTooltip'](arg1);
}

export function GetGitCommitFilter(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetGitCommitFilter'](arg1, arg2, arg3);
}

export function GetGitConfig() {
  return window['go']['app']['App']['GetGitConfig']();
}

export function GetGitFileContent(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetGitFileContent'](arg1, arg2, arg3, arg4);
}

export function GetIntegrationProperties(arg1) {
  return window['go']['app']['App']['GetIntegrationProperties'](arg1);
}

export function GetKernelPythonVersion(arg1) {
  return window['go']['app']['App']['GetKernelPythonVersion'](arg1);
}

export function GetLocalFilePreview(arg1, arg2) {
  return window['go']['app']['App']['GetLocalFilePreview'](arg1, arg2);
}

export function GetMCPSessionConfig(arg1) {
  return window['go']['app']['App']['GetMCPSessionConfig'](arg1);
}

export function GetNotebookCompletions(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetNotebookCompletions'](arg1, arg2, arg3, arg4);
}

export function GetNotebookHover(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetNotebookHover'](arg1, arg2, arg3, arg4);
}

export function GetNotebookPrefs() {
  return window['go']['app']['App']['GetNotebookPrefs']();
}

export function GetNotebookQueryWarehouse(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetNotebookQueryWarehouse'](arg1, arg2, arg3);
}

export function GetObjectDDL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetObjectDDL'](arg1, arg2, arg3, arg4, arg5);
}

export function GetObjectDependencies(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetObjectDependencies'](arg1, arg2, arg3, arg4, arg5);
}

export function GetObjectProperties(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetObjectProperties'](arg1, arg2, arg3, arg4);
}

export function GetPipRegistryConfig() {
  return window['go']['app']['App']['GetPipRegistryConfig']();
}

export function GetPipeCopyHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetPipeCopyHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetPipeStatus(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPipeStatus'](arg1, arg2, arg3);
}

export function GetPlatformOS() {
  return window['go']['app']['App']['GetPlatformOS']();
}

export function GetProcedureParams(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetProcedureParams'](arg1, arg2, arg3, arg4);
}

export function GetQueryHistory(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['GetQueryHistory'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetQueryOperatorStats(arg1) {
  return window['go']['app']['App']['GetQueryOperatorStats'](arg1);
}

export function GetQuotedIdentifiersIgnoreCase() {
  return window['go']['app']['App']['GetQuotedIdentifiersIgnoreCase']();
}

export function GetRoleDDL(arg1) {
  return window['go']['app']['App']['GetRoleDDL'](arg1);
}

export function GetSchemaCrossDeps(arg1, arg2) {
  return window['go']['app']['App']['GetSchemaCrossDeps'](arg1, arg2);
}

export function GetSchemaForeignKeys(arg1, arg2) {
  return window['go']['app']['App']['GetSchemaForeignKeys'](arg1, arg2);
}

export function GetSchemaRetentionDays(arg1, arg2) {
  return window['go']['app']['App']['GetSchemaRetentionDays'](arg1, arg2);
}

export function GetSessionConfig() {
  return window['go']['app']['App']['GetSessionConfig']();
}

export function GetSessionContext(arg1) {
  return window['go']['app']['App']['GetSessionContext'](arg1);
}

export function GetSessionInitMode() {
  return window['go']['app']['App']['GetSessionInitMode']();
}

export function GetSessionParameters() {
  return window['go']['app']['App']['GetSessionParameters']();
}

export function GetSessionVariables() {
  return window['go']['app']['App']['GetSessionVariables']();
}

export function GetSnowflakeCLIConfigPath() {
  return window['go']['app']['App']['GetSnowflakeCLIConfigPath']();
}

export function GetSnowparkConfig() {
  return window['go']['app']['App']['GetSnowparkConfig']();
}

export function GetSnowsightURL() {
  return window['go']['app']['App']['GetSnowsightURL']();
}

export function GetStageFilePreview(arg1, arg2) {
  return window['go']['app']['App']['GetStageFilePreview'](arg1, arg2);
}

export function GetSystemRAMGB() {
  return window['go']['app']['App']['GetSystemRAMGB']();
}

export function GetTabSessionID(arg1) {
  return window['go']['app']['App']['GetTabSessionID'](arg1);
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function GetTableColumnsWithTypes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableColumnsWithTypes'](arg1, arg2, arg3);
}

export function GetTableForeignKeys(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableForeignKeys'](arg1, arg2, arg3);
}

export function GetTableRetentionDays(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableRetentionDays'](arg1, arg2, arg3);
}

export function GetTableSettings(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableSettings'](arg1, arg2, arg3);
}

export function GetTaskRunHistory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetTaskRunHistory'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTaskStatuses(arg1, arg2) {
  return window['go']['app']['App']['GetTaskStatuses'](arg1, arg2);
}

export function GetTopologicalOrder(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTopologicalOrder'](arg1, arg2, arg3);
}

export function GetUserDDL(arg1) {
  return window['go']['app']['App']['GetUserDDL'](arg1);
}

export function GetWarehouseDDL(arg1) {
  return window['go']['app']['App']['GetWarehouseDDL'](arg1);
}

export function GetWarehouseMeteringHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetWarehouseMeteringHistory'](arg1, arg2, arg3);
}

export function GetWarehouseParameters(arg1) {
  return window['go']['app']['App']['GetWarehouseParameters'](arg1);
}

export function GitCheckoutBranch(arg1, arg2) {
  return window['go']['app']['App']['GitCheckoutBranch'](arg1, arg2);
}

export function GitCheckoutRemoteBranch(arg1, arg2) {
  return window['go']['app']['App']['GitCheckoutRemoteBranch'](arg1, arg2);
}

export function GitClone(arg1) {
  return window['go']['app']['App']['GitClone'](arg1);
}

export function GitCommitAndPush(arg1) {
  return window['go']['app']['App']['GitCommitAndPush'](arg1);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['app']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitDeleteBranch(arg1, arg2) {
  return window['go']['app']['App']['GitDeleteBranch'](arg1, arg2);
}

export function GitDeleteRemoteBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitDeleteRemoteBranch'](arg1, arg2, arg3);
}

export function GitFetch(arg1, arg2) {
  return window['go']['app']['App']['GitFetch'](arg1, arg2);
}

export function GitGetHeadFileContent(arg1) {
  return window['go']['app']['App']['GitGetHeadFileContent'](arg1);
}

export function GitInitWithRemote(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitInitWithRemote'](arg1, arg2, arg3);
}

export function GitListBranches(arg1) {
  return window['go']['app']['App']['GitListBranches'](arg1);
}

export function GitLoginWithOAuth(arg1) {
  return window['go']['app']['App']['GitLoginWithOAuth'](arg1);
}

export function GitLookupCredentials(arg1) {
  return window['go']['app']['App']['GitLookupCredentials'](arg1);
}

export function GitMergeBranch(arg1, arg2) {
  return window['go']['app']['App']['GitMergeBranch'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['app']['App']['GitPull'](arg1);
}

export function GitPushBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitPushBranch'](arg1, arg2, arg3);
}

export function GitResetHard(arg1) {
  return window['go']['app']['App']['GitResetHard'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['app']['App']['GitStatus'](arg1);
}

export function GitUpdateRemoteURL(arg1, arg2) {
  return window['go']['app']['App']['GitUpdateRemoteURL'](arg1, arg2);
}

export function ImportTableData(arg1) {
  return window['go']['app']['App']['ImportTableData'](arg1);
}

export function InitTabSession(arg1) {
  return window['go']['app']['App']['InitTabSession'](arg1);
}

export function InstallCondaEnv() {
  return window['go']['app']['App']['InstallCondaEnv']();
}

export function InstallEnvPackage(arg1) {
  return window['go']['app']['App']['InstallEnvPackage'](arg1);
}

export function InstallJupyterNotebook() {
  return window['go']['app']['App']['InstallJupyterNotebook']();
}

export function InstallJupyterVenv() {
  return window['go']['app']['App']['InstallJupyterVenv']();
}

export function InstallSnowparkPackage() {
  return window['go']['app']['App']['InstallSnowparkPackage']();
}

export function InstallSnowparkVenv(arg1) {
  return window['go']['app']['App']['InstallSnowparkVenv'](arg1);
}

export function InstallVenvEnv() {
  return window['go']['app']['App']['InstallVenvEnv']();
}

export function IsAppleSilicon() {
  return window['go']['app']['App']['IsAppleSilicon']();
}

export function IsBoolean(arg1) {
  return window['go']['app']['App']['IsBoolean'](arg1);
}

export function IsConnected() {
  return window['go']['app']['App']['IsConnected']();
}

export function IsNumeric(arg1) {
  return window['go']['app']['App']['IsNumeric'](arg1);
}

export function ListAIModels(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListAIModels'](arg1, arg2, arg3);
}

export function ListApiIntegrations() {
  return window['go']['app']['App']['ListApiIntegrations']();
}

export function ListAvailableRoles() {
  return window['go']['app']['App']['ListAvailableRoles']();
}

export function ListBackupPolicies() {
  return window['go']['app']['App']['ListBackupPolicies']();
}

export function ListBackupSets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListBackupSets'](arg1, arg2, arg3, arg4, arg5);
}

export function ListBackups(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListBackups'](arg1, arg2, arg3);
}

export function ListBasicObjects(arg1, arg2) {
  return window['go']['app']['App']['ListBasicObjects'](arg1, arg2);
}

export function ListDatabases() {
  return window['go']['app']['App']['ListDatabases']();
}

export function ListDbtProjectEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListDbtProjectEntries'](arg1, arg2, arg3, arg4);
}

export function ListDbtProjectVersions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListDbtProjectVersions'](arg1, arg2, arg3);
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ListDroppedDatabases() {
  return window['go']['app']['App']['ListDroppedDatabases']();
}

export function ListDroppedSchemas(arg1) {
  return window['go']['app']['App']['ListDroppedSchemas'](arg1);
}

export function ListDroppedTables(arg1, arg2) {
  return window['go']['app']['App']['ListDroppedTables'](arg1, arg2);
}

export function ListEnvPackages() {
  return window['go']['app']['App']['ListEnvPackages']();
}

export function ListExportableDatabases() {
  return window['go']['app']['App']['ListExportableDatabases']();
}

export function ListExternalAccessIntegrations() {
  return window['go']['app']['App']['ListExternalAccessIntegrations']();
}

export function ListExternalVolumes() {
  return window['go']['app']['App']['ListExternalVolumes']();
}

export function ListFileFormats(arg1, arg2) {
  return window['go']['app']['App']['ListFileFormats'](arg1, arg2);
}

export function ListFinalizableTasks(arg1, arg2) {
  return window['go']['app']['App']['ListFinalizableTasks'](arg1, arg2);
}

export function ListGitBranches(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListGitBranches'](arg1, arg2, arg3);
}

export function ListGitRepoEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListGitRepoEntries'](arg1, arg2, arg3, arg4);
}

export function ListGitTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListGitTags'](arg1, arg2, arg3);
}

export function ListIntegrations(arg1) {
  return window['go']['app']['App']['ListIntegrations'](arg1);
}

export function ListMCPSessions() {
  return window['go']['app']['App']['ListMCPSessions']();
}

export function ListNotificationIntegrations() {
  return window['go']['app']['App']['ListNotificationIntegrations']();
}

export function ListObjects(arg1, arg2) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2);
}

export function ListRoles() {
  return window['go']['app']['App']['ListRoles']();
}

export function ListRootTasks(arg1, arg2) {
  return window['go']['app']['App']['ListRootTasks'](arg1, arg2);
}

export function ListSchemas(arg1) {
  return window['go']['app']['App']['ListSchemas'](arg1);
}

export function ListSecretsInAccount() {
  return window['go']['app']['App']['ListSecretsInAccount']();
}

export function ListSecurityIntegrations() {
  return window['go']['app']['App']['ListSecurityIntegrations']();
}

export function ListStageEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListStageEntries'](arg1, arg2, arg3, arg4);
}

export function ListStageFiles(arg1, arg2) {
  return window['go']['app']['App']['ListStageFiles'](arg1, arg2);
}

export function ListSupportedDbtVersions() {
  return window['go']['app']['App']['ListSupportedDbtVersions']();
}

export function ListSystemPythons() {
  return window['go']['app']['App']['ListSystemPythons']();
}

export function ListUsers() {
  return window['go']['app']['App']['ListUsers']();
}

export function ListWarehouses() {
  return window['go']['app']['App']['ListWarehouses']();
}

export function ListWorkspaceEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListWorkspaceEntries'](arg1, arg2, arg3, arg4);
}

export function ListWorkspaces() {
  return window['go']['app']['App']['ListWorkspaces']();
}

export function LoadNotebookBreakpoints(arg1) {
  return window['go']['app']['App']['LoadNotebookBreakpoints'](arg1);
}

export function LoadSnowflakeCLIConfig() {
  return window['go']['app']['App']['LoadSnowflakeCLIConfig']();
}

export function MakeNotebookLive(arg1, arg2, arg3) {
  return window['go']['app']['App']['MakeNotebookLive'](arg1, arg2, arg3);
}

export function NeedsQuotes(arg1) {
  return window['go']['app']['App']['NeedsQuotes'](arg1);
}

export function NewNotebook() {
  return window['go']['app']['App']['NewNotebook']();
}

export function NotebookUseContext(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['NotebookUseContext'](arg1, arg2, arg3, arg4, arg5);
}

export function PickCACertFile() {
  return window['go']['app']['App']['PickCACertFile']();
}

export function PickDataFile() {
  return window['go']['app']['App']['PickDataFile']();
}

export function PickDataFileByFormat(arg1) {
  return window['go']['app']['App']['PickDataFileByFormat'](arg1);
}

export function PickDataFilesByFormat(arg1) {
  return window['go']['app']['App']['PickDataFilesByFormat'](arg1);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function PickFileForFormatPreview() {
  return window['go']['app']['App']['PickFileForFormatPreview']();
}

export function PickNotebookFile() {
  return window['go']['app']['App']['PickNotebookFile']();
}

export function PickOpenFile() {
  return window['go']['app']['App']['PickOpenFile']();
}

export function PickSaveExportFile(arg1, arg2) {
  return window['go']['app']['App']['PickSaveExportFile'](arg1, arg2);
}

export function PickSaveFile(arg1) {
  return window['go']['app']['App']['PickSaveFile'](arg1);
}

export function PickSnowflakeCLIConfigPath() {
  return window['go']['app']['App']['PickSnowflakeCLIConfigPath']();
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function ReadFileHead(arg1, arg2) {
  return window['go']['app']['App']['ReadFileHead'](arg1, arg2);
}

export function ReadNotebook(arg1) {
  return window['go']['app']['App']['ReadNotebook'](arg1);
}

export function RemoveStageFiles(arg1, arg2) {
  return window['go']['app']['App']['RemoveStageFiles'](arg1, arg2);
}

export function RenameFile(arg1, arg2) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['app']['App']['RenameProfile'](arg1, arg2);
}

export function ResetPipRegistryConfig() {
  return window['go']['app']['App']['ResetPipRegistryConfig']();
}

export function ResizeShell(arg1, arg2) {
  return window['go']['app']['App']['ResizeShell'](arg1, arg2);
}

export function RestoreFromBackup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['RestoreFromBackup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ResumeTaskList(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResumeTaskList'](arg1, arg2, arg3);
}

export function RevealInFinder(arg1) {
  return window['go']['app']['App']['RevealInFinder'](arg1);
}

export function RunExplain(arg1, arg2) {
  return window['go']['app']['App']['RunExplain'](arg1, arg2);
}

export function RunNotebookCell(arg1, arg2, arg3) {
  return window['go']['app']['App']['RunNotebookCell'](arg1, arg2, arg3);
}

export function RunNotebookCellSql(arg1, arg2) {
  return window['go']['app']['App']['RunNotebookCellSql'](arg1, arg2);
}

export function RunNotebookSql(arg1) {
  return window['go']['app']['App']['RunNotebookSql'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['app']['App']['SaveAIConfig'](arg1);
}

export function SaveBinaryFile(arg1, arg2) {
  return window['go']['app']['App']['SaveBinaryFile'](arg1, arg2);
}

export function SaveEditorPrefs(arg1) {
  return window['go']['app']['App']['SaveEditorPrefs'](arg1);
}

export function SaveFeatureFlags(arg1) {
  return window['go']['app']['App']['SaveFeatureFlags'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['app']['App']['SaveFile'](arg1, arg2);
}

export function SaveGitConfig(arg1) {
  return window['go']['app']['App']['SaveGitConfig'](arg1);
}

export function SaveNotebook(arg1, arg2) {
  return window['go']['app']['App']['SaveNotebook'](arg1, arg2);
}

export function SaveNotebookBreakpoints(arg1, arg2) {
  return window['go']['app']['App']['SaveNotebookBreakpoints'](arg1, arg2);
}

export function SaveNotebookPrefs(arg1) {
  return window['go']['app']['App']['SaveNotebookPrefs'](arg1);
}

export function SavePipRegistryConfig(arg1) {
  return window['go']['app']['App']['SavePipRegistryConfig'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['app']['App']['SaveProfile'](arg1);
}

export function SaveSessionConfig(arg1) {
  return window['go']['app']['App']['SaveSessionConfig'](arg1);
}

export function SaveSnowparkConfig(arg1) {
  return window['go']['app']['App']['SaveSnowparkConfig'](arg1);
}

export function SaveSnowparkPythonPath(arg1) {
  return window['go']['app']['App']['SaveSnowparkPythonPath'](arg1);
}

export function SaveSnowparkVenvPath(arg1) {
  return window['go']['app']['App']['SaveSnowparkVenvPath'](arg1);
}

export function ScanMigrationSource(arg1) {
  return window['go']['app']['App']['ScanMigrationSource'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SetColumnComment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SetColumnComment'](arg1, arg2, arg3, arg4, arg5);
}

export function SetDefaultProfile(arg1) {
  return window['go']['app']['App']['SetDefaultProfile'](arg1);
}

export function SetGitCommitFilter(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetGitCommitFilter'](arg1, arg2, arg3, arg4);
}

export function SetNotebookQueryWarehouse(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetNotebookQueryWarehouse'](arg1, arg2, arg3, arg4);
}

export function SetSessionParameter(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetSessionParameter'](arg1, arg2, arg3);
}

export function SetSessionVariable(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetSessionVariable'](arg1, arg2, arg3);
}

export function SetUserPublicKey(arg1, arg2) {
  return window['go']['app']['App']['SetUserPublicKey'](arg1, arg2);
}

export function StartDapProxy() {
  return window['go']['app']['App']['StartDapProxy']();
}

export function StartFileWatcher(arg1) {
  return window['go']['app']['App']['StartFileWatcher'](arg1);
}

export function StartMCPSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StartMCPSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartNotebookSession(arg1) {
  return window['go']['app']['App']['StartNotebookSession'](arg1);
}

export function StartQuery(arg1, arg2) {
  return window['go']['app']['App']['StartQuery'](arg1, arg2);
}

export function StartShell(arg1, arg2) {
  return window['go']['app']['App']['StartShell'](arg1, arg2);
}

export function StopDapProxy() {
  return window['go']['app']['App']['StopDapProxy']();
}

export function StopFileWatcher() {
  return window['go']['app']['App']['StopFileWatcher']();
}

export function StopMCPSession(arg1) {
  return window['go']['app']['App']['StopMCPSession'](arg1);
}

export function StopNotebookSession(arg1) {
  return window['go']['app']['App']['StopNotebookSession'](arg1);
}

export function StopShell() {
  return window['go']['app']['App']['StopShell']();
}

export function SuspendTaskGraph(arg1, arg2, arg3) {
  return window['go']['app']['App']['SuspendTaskGraph'](arg1, arg2, arg3);
}

export function SuspendTaskList(arg1, arg2, arg3) {
  return window['go']['app']['App']['SuspendTaskList'](arg1, arg2, arg3);
}

export function TaskHasChildren(arg1, arg2, arg3) {
  return window['go']['app']['App']['TaskHasChildren'](arg1, arg2, arg3);
}

export function TestAIModel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['TestAIModel'](arg1, arg2, arg3, arg4, arg5);
}

export function UninstallEnvPackage(arg1) {
  return window['go']['app']['App']['UninstallEnvPackage'](arg1);
}

export function UploadFileToStage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['UploadFileToStage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UseDatabase(arg1, arg2) {
  return window['go']['app']['App']['UseDatabase'](arg1, arg2);
}

export function UseRole(arg1, arg2) {
  return window['go']['app']['App']['UseRole'](arg1, arg2);
}

export function UseSchema(arg1, arg2) {
  return window['go']['app']['App']['UseSchema'](arg1, arg2);
}

export function UseWarehouse(arg1, arg2) {
  return window['go']['app']['App']['UseWarehouse'](arg1, arg2);
}

export function VenvFolderExists() {
  return window['go']['app']['App']['VenvFolderExists']();
}

export function WaitForQueryResult(arg1) {
  return window['go']['app']['App']['WaitForQueryResult'](arg1);
}

export function WriteShell(arg1) {
  return window['go']['app']['App']['WriteShell'](arg1);
}
