// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackup(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddBackup'](arg1, arg2, arg3);
}

export function AddRecentDir(arg1) {
  return window['go']['app']['App']['AddRecentDir'](arg1);
}

export function AlterAgent(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterAgent'](arg1, arg2, arg3, arg4);
}

export function AlterAggregationPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterAggregationPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterAlert(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterAlert'](arg1, arg2, arg3, arg4);
}

export function AlterAuthenticationPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterAuthenticationPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterBackupPolicy(arg1, arg2) {
  return window['go']['app']['App']['AlterBackupPolicy'](arg1, arg2);
}

export function AlterBackupSet(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterBackupSet'](arg1, arg2, arg3, arg4);
}

export function AlterContact(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterContact'](arg1, arg2, arg3, arg4);
}

export function AlterCortexSearchService(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterCortexSearchService'](arg1, arg2, arg3, arg4);
}

export function AlterDataMetricFunction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AlterDataMetricFunction'](arg1, arg2, arg3, arg4, arg5);
}

export function AlterDataset(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterDataset'](arg1, arg2, arg3, arg4);
}

export function AlterDynamicTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterDynamicTable'](arg1, arg2, arg3, arg4);
}

export function AlterEventTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterEventTable'](arg1, arg2, arg3, arg4);
}

export function AlterExternalAgent(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterExternalAgent'](arg1, arg2, arg3, arg4);
}

export function AlterExternalFunction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AlterExternalFunction'](arg1, arg2, arg3, arg4, arg5);
}

export function AlterExternalTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterExternalTable'](arg1, arg2, arg3, arg4);
}

export function AlterFunction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AlterFunction'](arg1, arg2, arg3, arg4, arg5);
}

export function AlterGateway(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterGateway'](arg1, arg2, arg3, arg4);
}

export function AlterHybridTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterHybridTable'](arg1, arg2, arg3, arg4);
}

export function AlterIcebergTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterIcebergTable'](arg1, arg2, arg3, arg4);
}

export function AlterImageRepository(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterImageRepository'](arg1, arg2, arg3, arg4);
}

export function AlterJoinPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterJoinPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterMaskingPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterMaskingPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterMaterializedView(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterMaterializedView'](arg1, arg2, arg3, arg4);
}

export function AlterModel(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterModel'](arg1, arg2, arg3, arg4);
}

export function AlterModelMonitor(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterModelMonitor'](arg1, arg2, arg3, arg4);
}

export function AlterNetworkRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterNetworkRule'](arg1, arg2, arg3, arg4);
}

export function AlterPackagesPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterPackagesPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterPasswordPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterPasswordPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterPipe(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterPipe'](arg1, arg2, arg3, arg4);
}

export function AlterPrivacyPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterPrivacyPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterProcedure(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AlterProcedure'](arg1, arg2, arg3, arg4, arg5);
}

export function AlterProjectionPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterProjectionPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterRowAccessPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterRowAccessPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterSemanticView(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterSemanticView'](arg1, arg2, arg3, arg4);
}

export function AlterSequence(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterSequence'](arg1, arg2, arg3, arg4);
}

export function AlterService(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterService'](arg1, arg2, arg3, arg4);
}

export function AlterSessionPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterSessionPolicy'](arg1, arg2, arg3, arg4);
}

export function AlterStage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterStage'](arg1, arg2, arg3, arg4);
}

export function AlterStorageLifecyclePolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterStorageLifecyclePolicy'](arg1, arg2, arg3, arg4);
}

export function AlterStream(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterStream'](arg1, arg2, arg3, arg4);
}

export function AlterStreamlit(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterStreamlit'](arg1, arg2, arg3, arg4);
}

export function AlterTableProperty(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AlterTableProperty'](arg1, arg2, arg3, arg4, arg5);
}

export function AlterTag(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterTag'](arg1, arg2, arg3, arg4);
}

export function AlterTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterTask'](arg1, arg2, arg3, arg4);
}

export function AlterView(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterView'](arg1, arg2, arg3, arg4);
}

export function AlterWarehouseAbortAllQueries(arg1) {
  return window['go']['app']['App']['AlterWarehouseAbortAllQueries'](arg1);
}

export function AlterWarehouseProperty(arg1, arg2, arg3) {
  return window['go']['app']['App']['AlterWarehouseProperty'](arg1, arg2, arg3);
}

export function AlterWarehouseRename(arg1, arg2) {
  return window['go']['app']['App']['AlterWarehouseRename'](arg1, arg2);
}

export function AlterWarehouseResume(arg1) {
  return window['go']['app']['App']['AlterWarehouseResume'](arg1);
}

export function AlterWarehouseSuspend(arg1) {
  return window['go']['app']['App']['AlterWarehouseSuspend'](arg1);
}

export function AnalyzeMigration(arg1, arg2) {
  return window['go']['app']['App']['AnalyzeMigration'](arg1, arg2);
}

export function AuthenticationPolicyBagOptions() {
  return window['go']['app']['App']['AuthenticationPolicyBagOptions']();
}

export function AuthenticationPolicyClientDriverVersions() {
  return window['go']['app']['App']['AuthenticationPolicyClientDriverVersions']();
}

export function AuthenticationPolicyClientDrivers() {
  return window['go']['app']['App']['AuthenticationPolicyClientDrivers']();
}

export function AuthenticationPolicyListParams() {
  return window['go']['app']['App']['AuthenticationPolicyListParams']();
}

export function AuthenticationPolicyMFAEnrollmentOptions() {
  return window['go']['app']['App']['AuthenticationPolicyMFAEnrollmentOptions']();
}

export function BuildAddColumnSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildAddColumnSql'](arg1, arg2, arg3, arg4);
}

export function BuildAddDbtProjectVersionSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildAddDbtProjectVersionSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildAlterDbtProjectSetSql(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['BuildAlterDbtProjectSetSql'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function BuildAlterStageSql(arg1) {
  return window['go']['app']['App']['BuildAlterStageSql'](arg1);
}

export function BuildApiIntegrationPreviewSQL(arg1) {
  return window['go']['app']['App']['BuildApiIntegrationPreviewSQL'](arg1);
}

export function BuildCallStatement(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildCallStatement'](arg1, arg2, arg3, arg4);
}

export function BuildChangeColumnTypeSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildChangeColumnTypeSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildClientPolicyValue(arg1) {
  return window['go']['app']['App']['BuildClientPolicyValue'](arg1);
}

export function BuildCreateAgentSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateAgentSql'](arg1, arg2, arg3);
}

export function BuildCreateAggregationPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateAggregationPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateAlertSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateAlertSql'](arg1, arg2, arg3);
}

export function BuildCreateAuthenticationPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateAuthenticationPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateContactSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateContactSql'](arg1, arg2, arg3);
}

export function BuildCreateCortexSearchServiceSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateCortexSearchServiceSql'](arg1, arg2, arg3);
}

export function BuildCreateDataMetricFunctionSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateDataMetricFunctionSql'](arg1, arg2, arg3);
}

export function BuildCreateDatasetSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateDatasetSql'](arg1, arg2, arg3);
}

export function BuildCreateDbtProjectSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateDbtProjectSql'](arg1, arg2, arg3);
}

export function BuildCreateDynamicTableSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateDynamicTableSql'](arg1, arg2, arg3);
}

export function BuildCreateEventTableSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateEventTableSql'](arg1, arg2, arg3);
}

export function BuildCreateExternalAgentSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateExternalAgentSql'](arg1, arg2, arg3);
}

export function BuildCreateExternalFunctionSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateExternalFunctionSql'](arg1, arg2, arg3);
}

export function BuildCreateExternalTableSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateExternalTableSql'](arg1, arg2, arg3);
}

export function BuildCreateFileFormatSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateFileFormatSql'](arg1, arg2, arg3);
}

export function BuildCreateFunctionSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateFunctionSql'](arg1, arg2, arg3);
}

export function BuildCreateGatewaySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateGatewaySql'](arg1, arg2, arg3);
}

export function BuildCreateGitRepositorySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateGitRepositorySql'](arg1, arg2, arg3);
}

export function BuildCreateHybridTableSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateHybridTableSql'](arg1, arg2, arg3);
}

export function BuildCreateIcebergTableSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateIcebergTableSql'](arg1, arg2, arg3);
}

export function BuildCreateImageRepositorySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateImageRepositorySql'](arg1, arg2, arg3);
}

export function BuildCreateJoinPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateJoinPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateMCPServerSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateMCPServerSql'](arg1, arg2, arg3);
}

export function BuildCreateMaskingPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateMaskingPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateMaterializedViewSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateMaterializedViewSql'](arg1, arg2, arg3);
}

export function BuildCreateModelMonitorSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateModelMonitorSql'](arg1, arg2, arg3);
}

export function BuildCreateModelSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateModelSql'](arg1, arg2, arg3);
}

export function BuildCreateNetworkRuleSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateNetworkRuleSql'](arg1, arg2, arg3);
}

export function BuildCreatePackagesPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreatePackagesPolicySql'](arg1, arg2, arg3);
}

export function BuildCreatePasswordPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreatePasswordPolicySql'](arg1, arg2, arg3);
}

export function BuildCreatePipeSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreatePipeSql'](arg1, arg2, arg3);
}

export function BuildCreatePrivacyPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreatePrivacyPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateProcedureSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateProcedureSql'](arg1, arg2, arg3);
}

export function BuildCreateProjectionPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateProjectionPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateRowAccessPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateRowAccessPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateSecretSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateSecretSql'](arg1, arg2, arg3);
}

export function BuildCreateSemanticViewSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateSemanticViewSql'](arg1, arg2, arg3);
}

export function BuildCreateSequenceSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateSequenceSql'](arg1, arg2, arg3);
}

export function BuildCreateServiceSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateServiceSql'](arg1, arg2, arg3);
}

export function BuildCreateSessionPolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateSessionPolicySql'](arg1, arg2, arg3);
}

export function BuildCreateStageSql(arg1) {
  return window['go']['app']['App']['BuildCreateStageSql'](arg1);
}

export function BuildCreateStorageLifecyclePolicySql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateStorageLifecyclePolicySql'](arg1, arg2, arg3);
}

export function BuildCreateStreamSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateStreamSql'](arg1, arg2, arg3);
}

export function BuildCreateStreamlitSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateStreamlitSql'](arg1, arg2, arg3);
}

export function BuildCreateTagSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateTagSql'](arg1, arg2, arg3);
}

export function BuildCreateViewSql(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildCreateViewSql'](arg1, arg2, arg3);
}

export function BuildDropColumnDefaultSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildDropColumnDefaultSql'](arg1, arg2, arg3, arg4);
}

export function BuildDropColumnNotNullSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildDropColumnNotNullSql'](arg1, arg2, arg3, arg4);
}

export function BuildDropColumnSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildDropColumnSql'](arg1, arg2, arg3, arg4);
}

export function BuildExecuteDbtProjectSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildExecuteDbtProjectSql'](arg1, arg2, arg3, arg4);
}

export function BuildFunctionSelectStatement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildFunctionSelectStatement'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildJoinSQL(arg1) {
  return window['go']['app']['App']['BuildJoinSQL'](arg1);
}

export function BuildJoinState(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildJoinState'](arg1, arg2, arg3);
}

export function BuildMFAPolicyValue(arg1) {
  return window['go']['app']['App']['BuildMFAPolicyValue'](arg1);
}

export function BuildModifyGitRepositorySql(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['BuildModifyGitRepositorySql'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BuildModifySecretSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildModifySecretSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildPATPolicyValue(arg1) {
  return window['go']['app']['App']['BuildPATPolicyValue'](arg1);
}

export function BuildRefreshPipeSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildRefreshPipeSql'](arg1, arg2, arg3, arg4);
}

export function BuildRenameColumnSql(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['BuildRenameColumnSql'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BuildSetColumnCommentSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildSetColumnCommentSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildSetColumnDefaultSql(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BuildSetColumnDefaultSql'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildSetColumnMaskingPolicySql(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['BuildSetColumnMaskingPolicySql'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BuildSetColumnNotNullSql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildSetColumnNotNullSql'](arg1, arg2, arg3, arg4);
}

export function BuildUnsetColumnMaskingPolicySql(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BuildUnsetColumnMaskingPolicySql'](arg1, arg2, arg3, arg4);
}

export function BuildWorkloadIdentityPolicyValue(arg1) {
  return window['go']['app']['App']['BuildWorkloadIdentityPolicyValue'](arg1);
}

export function CanCreateIntegration(arg1) {
  return window['go']['app']['App']['CanCreateIntegration'](arg1);
}

export function CanCreateUsers(arg1) {
  return window['go']['app']['App']['CanCreateUsers'](arg1);
}

export function CanManageUsers(arg1) {
  return window['go']['app']['App']['CanManageUsers'](arg1);
}

export function CanModifyUserAuth(arg1) {
  return window['go']['app']['App']['CanModifyUserAuth'](arg1);
}

export function CanViewWarehouseMeteringHistory() {
  return window['go']['app']['App']['CanViewWarehouseMeteringHistory']();
}

export function CancelConnect() {
  return window['go']['app']['App']['CancelConnect']();
}

export function CancelExport() {
  return window['go']['app']['App']['CancelExport']();
}

export function CancelMigration() {
  return window['go']['app']['App']['CancelMigration']();
}

export function CancelQuery(arg1) {
  return window['go']['app']['App']['CancelQuery'](arg1);
}

export function CheckAvailableKeyTools() {
  return window['go']['app']['App']['CheckAvailableKeyTools']();
}

export function CheckPythonSyntax(arg1, arg2, arg3) {
  return window['go']['app']['App']['CheckPythonSyntax'](arg1, arg2, arg3);
}

export function CheckSnowparkEnv() {
  return window['go']['app']['App']['CheckSnowparkEnv']();
}

export function ClearDefaultProfile() {
  return window['go']['app']['App']['ClearDefaultProfile']();
}

export function ClearERDesignerState() {
  return window['go']['app']['App']['ClearERDesignerState']();
}

export function ClearObjectCache() {
  return window['go']['app']['App']['ClearObjectCache']();
}

export function ClearObjectCacheForDatabase(arg1) {
  return window['go']['app']['App']['ClearObjectCacheForDatabase'](arg1);
}

export function ClearQueryLog() {
  return window['go']['app']['App']['ClearQueryLog']();
}

export function ClearQueryResult(arg1) {
  return window['go']['app']['App']['ClearQueryResult'](arg1);
}

export function ClearRecentDirs() {
  return window['go']['app']['App']['ClearRecentDirs']();
}

export function CloneChildTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CloneChildTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CloneProfile(arg1, arg2) {
  return window['go']['app']['App']['CloneProfile'](arg1, arg2);
}

export function CloseTabSession(arg1) {
  return window['go']['app']['App']['CloseTabSession'](arg1);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function CopyFile(arg1, arg2) {
  return window['go']['app']['App']['CopyFile'](arg1, arg2);
}

export function CreateApiIntegration(arg1) {
  return window['go']['app']['App']['CreateApiIntegration'](arg1);
}

export function CreateBackupPolicy(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['CreateBackupPolicy'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateBackupSet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['CreateBackupSet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateCatalogIntegration(arg1) {
  return window['go']['app']['App']['CreateCatalogIntegration'](arg1);
}

export function CreateDbtProject(arg1, arg2) {
  return window['go']['app']['App']['CreateDbtProject'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['app']['App']['CreateDirectory'](arg1);
}

export function CreateExternalAccessIntegration(arg1) {
  return window['go']['app']['App']['CreateExternalAccessIntegration'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['app']['App']['CreateFile'](arg1);
}

export function CreateHybridTableIndex(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CreateHybridTableIndex'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateMigrationSnapshot(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['CreateMigrationSnapshot'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateNotificationIntegration(arg1) {
  return window['go']['app']['App']['CreateNotificationIntegration'](arg1);
}

export function CreateSecurityIntegration(arg1) {
  return window['go']['app']['App']['CreateSecurityIntegration'](arg1);
}

export function CreateStorageIntegration(arg1) {
  return window['go']['app']['App']['CreateStorageIntegration'](arg1);
}

export function DebugNotebookCell(arg1, arg2, arg3) {
  return window['go']['app']['App']['DebugNotebookCell'](arg1, arg2, arg3);
}

export function DeleteDirectory(arg1) {
  return window['go']['app']['App']['DeleteDirectory'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteOldestBackup(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteOldestBackup'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DeleteVenvFolder() {
  return window['go']['app']['App']['DeleteVenvFolder']();
}

export function DeployNotebook(arg1) {
  return window['go']['app']['App']['DeployNotebook'](arg1);
}

export function DescribeAgent(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeAgent'](arg1, arg2, arg3);
}

export function DescribeAuthenticationPolicy(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeAuthenticationPolicy'](arg1, arg2, arg3);
}

export function DescribeDataMetricFunction(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DescribeDataMetricFunction'](arg1, arg2, arg3, arg4);
}

export function DescribeDbtProject(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeDbtProject'](arg1, arg2, arg3);
}

export function DescribeExternalFunction(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DescribeExternalFunction'](arg1, arg2, arg3, arg4);
}

export function DescribeGateway(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeGateway'](arg1, arg2, arg3);
}

export function DescribeMCPServer(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeMCPServer'](arg1, arg2, arg3);
}

export function DescribePasswordPolicy(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribePasswordPolicy'](arg1, arg2, arg3);
}

export function DescribeSemanticView(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeSemanticView'](arg1, arg2, arg3);
}

export function DescribeSessionPolicy(arg1, arg2, arg3) {
  return window['go']['app']['App']['DescribeSessionPolicy'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function DownloadFileFromStage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DownloadFileFromStage'](arg1, arg2, arg3, arg4);
}

export function DropBackupPolicy(arg1) {
  return window['go']['app']['App']['DropBackupPolicy'](arg1);
}

export function DropBackupSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropBackupSet'](arg1, arg2, arg3);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['app']['App']['DropDatabase'](arg1, arg2);
}

export function DropHybridTableIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DropHybridTableIndex'](arg1, arg2, arg3, arg4);
}

export function DropIntegration(arg1) {
  return window['go']['app']['App']['DropIntegration'](arg1);
}

export function DropSchema(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropSchema'](arg1, arg2, arg3);
}

export function DropTaskTree(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropTaskTree'](arg1, arg2, arg3);
}

export function DuplicateFile(arg1) {
  return window['go']['app']['App']['DuplicateFile'](arg1);
}

export function EnableTaskDependents(arg1, arg2, arg3) {
  return window['go']['app']['App']['EnableTaskDependents'](arg1, arg2, arg3);
}

export function ExecDDL(arg1) {
  return window['go']['app']['App']['ExecDDL'](arg1);
}

export function ExecuteAlert(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteAlert'](arg1, arg2, arg3);
}

export function ExecuteGitFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteGitFile'](arg1, arg2, arg3, arg4);
}

export function ExecuteMigration(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteMigration'](arg1, arg2, arg3, arg4);
}

export function ExecuteNotebook(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteNotebook'](arg1, arg2, arg3, arg4);
}

export function ExecuteQuery(arg1) {
  return window['go']['app']['App']['ExecuteQuery'](arg1);
}

export function ExecuteStageFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteStageFile'](arg1, arg2, arg3, arg4);
}

export function ExecuteTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ExecuteTask'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportAccountObjectsDDL(arg1) {
  return window['go']['app']['App']['ExportAccountObjectsDDL'](arg1);
}

export function ExportAllDatabasesDDL(arg1, arg2) {
  return window['go']['app']['App']['ExportAllDatabasesDDL'](arg1, arg2);
}

export function ExportDatabaseDDL(arg1, arg2) {
  return window['go']['app']['App']['ExportDatabaseDDL'](arg1, arg2);
}

export function ExportGraphDDL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportGraphDDL'](arg1, arg2, arg3, arg4);
}

export function ExportTableData(arg1) {
  return window['go']['app']['App']['ExportTableData'](arg1);
}

export function FetchNotebookContent(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchNotebookContent'](arg1, arg2, arg3);
}

export function FindJoinPaths(arg1, arg2) {
  return window['go']['app']['App']['FindJoinPaths'](arg1, arg2);
}

export function FormatAuthPolicyList(arg1) {
  return window['go']['app']['App']['FormatAuthPolicyList'](arg1);
}

export function FormatContactUsers(arg1) {
  return window['go']['app']['App']['FormatContactUsers'](arg1);
}

export function FormatCortexSearchAttributes(arg1) {
  return window['go']['app']['App']['FormatCortexSearchAttributes'](arg1);
}

export function FormatPackagesPolicyList(arg1) {
  return window['go']['app']['App']['FormatPackagesPolicyList'](arg1);
}

export function FormatSecondaryRoles(arg1) {
  return window['go']['app']['App']['FormatSecondaryRoles'](arg1);
}

export function FreezeRequirements(arg1) {
  return window['go']['app']['App']['FreezeRequirements'](arg1);
}

export function GenerateKeyPair(arg1, arg2, arg3) {
  return window['go']['app']['App']['GenerateKeyPair'](arg1, arg2, arg3);
}

export function GenerateMigrationScript(arg1, arg2, arg3) {
  return window['go']['app']['App']['GenerateMigrationScript'](arg1, arg2, arg3);
}

export function GetAIConfig() {
  return window['go']['app']['App']['GetAIConfig']();
}

export function GetAISuggestion(arg1) {
  return window['go']['app']['App']['GetAISuggestion'](arg1);
}

export function GetAdminLockedFlags() {
  return window['go']['app']['App']['GetAdminLockedFlags']();
}

export function GetAggregationPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetAggregationPolicyReferences'](arg1, arg2, arg3);
}

export function GetAllFunctionNames() {
  return window['go']['app']['App']['GetAllFunctionNames']();
}

export function GetAllTagReferences() {
  return window['go']['app']['App']['GetAllTagReferences']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAuthenticationPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetAuthenticationPolicyReferences'](arg1, arg2, arg3);
}

export function GetAvailableShells() {
  return window['go']['app']['App']['GetAvailableShells']();
}

export function GetClientVersionInfo() {
  return window['go']['app']['App']['GetClientVersionInfo']();
}

export function GetCollationLocales() {
  return window['go']['app']['App']['GetCollationLocales']();
}

export function GetCollationSpecifiers() {
  return window['go']['app']['App']['GetCollationSpecifiers']();
}

export function GetCollations() {
  return window['go']['app']['App']['GetCollations']();
}

export function GetColumnDetails(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetColumnDetails'](arg1, arg2, arg3, arg4);
}

export function GetColumnTagReferences(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetColumnTagReferences'](arg1, arg2, arg3, arg4);
}

export function GetCortexSearchServiceTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCortexSearchServiceTags'](arg1, arg2, arg3);
}

export function GetCurrentRegion() {
  return window['go']['app']['App']['GetCurrentRegion']();
}

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetDataMetricFunctionReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDataMetricFunctionReferences'](arg1, arg2, arg3);
}

export function GetDataMetricFunctionTags(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetDataMetricFunctionTags'](arg1, arg2, arg3, arg4);
}

export function GetDatabaseCrossDeps(arg1, arg2) {
  return window['go']['app']['App']['GetDatabaseCrossDeps'](arg1, arg2);
}

export function GetDatabaseRetentionDays(arg1) {
  return window['go']['app']['App']['GetDatabaseRetentionDays'](arg1);
}

export function GetDatabaseTableSummary(arg1) {
  return window['go']['app']['App']['GetDatabaseTableSummary'](arg1);
}

export function GetDefaultSessionConfig() {
  return window['go']['app']['App']['GetDefaultSessionConfig']();
}

export function GetERDiagramData(arg1) {
  return window['go']['app']['App']['GetERDiagramData'](arg1);
}

export function GetEditorPrefs() {
  return window['go']['app']['App']['GetEditorPrefs']();
}

export function GetEventTableParameters(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetEventTableParameters'](arg1, arg2, arg3);
}

export function GetExternalFunctionOptions() {
  return window['go']['app']['App']['GetExternalFunctionOptions']();
}

export function GetFeatureFlags() {
  return window['go']['app']['App']['GetFeatureFlags']();
}

export function GetFunctionInfo(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetFunctionInfo'](arg1, arg2, arg3, arg4);
}

export function GetFunctionSuggestions(arg1) {
  return window['go']['app']['App']['GetFunctionSuggestions'](arg1);
}

export function GetFunctionTooltip(arg1) {
  return window['go']['app']['App']['GetFunctionTooltip'](arg1);
}

export function GetGitCommitFilter(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetGitCommitFilter'](arg1, arg2, arg3);
}

export function GetGitConfig() {
  return window['go']['app']['App']['GetGitConfig']();
}

export function GetGitFileContent(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetGitFileContent'](arg1, arg2, arg3, arg4);
}

export function GetIntegrationProperties(arg1) {
  return window['go']['app']['App']['GetIntegrationProperties'](arg1);
}

export function GetJoinPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetJoinPolicyReferences'](arg1, arg2, arg3);
}

export function GetJoinPolicyTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetJoinPolicyTags'](arg1, arg2, arg3);
}

export function GetKernelPythonVersion(arg1) {
  return window['go']['app']['App']['GetKernelPythonVersion'](arg1);
}

export function GetLocalFilePreview(arg1, arg2) {
  return window['go']['app']['App']['GetLocalFilePreview'](arg1, arg2);
}

export function GetMCPSessionConfig(arg1) {
  return window['go']['app']['App']['GetMCPSessionConfig'](arg1);
}

export function GetMaskingPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetMaskingPolicyReferences'](arg1, arg2, arg3);
}

export function GetModelTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetModelTags'](arg1, arg2, arg3);
}

export function GetNotebookCompletions(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetNotebookCompletions'](arg1, arg2, arg3, arg4);
}

export function GetNotebookHover(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetNotebookHover'](arg1, arg2, arg3, arg4);
}

export function GetNotebookPrefs() {
  return window['go']['app']['App']['GetNotebookPrefs']();
}

export function GetNotebookQueryWarehouse(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetNotebookQueryWarehouse'](arg1, arg2, arg3);
}

export function GetObjectDDL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetObjectDDL'](arg1, arg2, arg3, arg4, arg5);
}

export function GetObjectDependencies(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetObjectDependencies'](arg1, arg2, arg3, arg4, arg5);
}

export function GetObjectProperties(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetObjectProperties'](arg1, arg2, arg3, arg4);
}

export function GetObjectTagReferences(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetObjectTagReferences'](arg1, arg2, arg3, arg4, arg5);
}

export function GetPasswordPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPasswordPolicyReferences'](arg1, arg2, arg3);
}

export function GetPipRegistryConfig() {
  return window['go']['app']['App']['GetPipRegistryConfig']();
}

export function GetPipeCopyHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetPipeCopyHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetPipeStatus(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPipeStatus'](arg1, arg2, arg3);
}

export function GetPlatformOS() {
  return window['go']['app']['App']['GetPlatformOS']();
}

export function GetPrivacyPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPrivacyPolicyReferences'](arg1, arg2, arg3);
}

export function GetPrivacyPolicyTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPrivacyPolicyTags'](arg1, arg2, arg3);
}

export function GetProcedureParams(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetProcedureParams'](arg1, arg2, arg3, arg4);
}

export function GetProjectionPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetProjectionPolicyReferences'](arg1, arg2, arg3);
}

export function GetQueryHistory(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['GetQueryHistory'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetQueryLogEntries() {
  return window['go']['app']['App']['GetQueryLogEntries']();
}

export function GetQueryOperatorStats(arg1) {
  return window['go']['app']['App']['GetQueryOperatorStats'](arg1);
}

export function GetQuotedIdentifiersIgnoreCase() {
  return window['go']['app']['App']['GetQuotedIdentifiersIgnoreCase']();
}

export function GetRoleDDL(arg1) {
  return window['go']['app']['App']['GetRoleDDL'](arg1);
}

export function GetRoutineProperties(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetRoutineProperties'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRowAccessPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetRowAccessPolicyReferences'](arg1, arg2, arg3);
}

export function GetSchemaCrossDeps(arg1, arg2) {
  return window['go']['app']['App']['GetSchemaCrossDeps'](arg1, arg2);
}

export function GetSchemaForeignKeys(arg1, arg2) {
  return window['go']['app']['App']['GetSchemaForeignKeys'](arg1, arg2);
}

export function GetSchemaRetentionDays(arg1, arg2) {
  return window['go']['app']['App']['GetSchemaRetentionDays'](arg1, arg2);
}

export function GetSemanticViewTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSemanticViewTags'](arg1, arg2, arg3);
}

export function GetServiceContainers(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetServiceContainers'](arg1, arg2, arg3);
}

export function GetServiceLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetServiceLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetSessionConfig() {
  return window['go']['app']['App']['GetSessionConfig']();
}

export function GetSessionContext(arg1) {
  return window['go']['app']['App']['GetSessionContext'](arg1);
}

export function GetSessionInitMode() {
  return window['go']['app']['App']['GetSessionInitMode']();
}

export function GetSessionParameters() {
  return window['go']['app']['App']['GetSessionParameters']();
}

export function GetSessionPolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSessionPolicyReferences'](arg1, arg2, arg3);
}

export function GetSessionVariables() {
  return window['go']['app']['App']['GetSessionVariables']();
}

export function GetSnowflakeCLIConfigPath() {
  return window['go']['app']['App']['GetSnowflakeCLIConfigPath']();
}

export function GetSnowparkConfig() {
  return window['go']['app']['App']['GetSnowparkConfig']();
}

export function GetSnowsightURL() {
  return window['go']['app']['App']['GetSnowsightURL']();
}

export function GetStageFilePreview(arg1, arg2) {
  return window['go']['app']['App']['GetStageFilePreview'](arg1, arg2);
}

export function GetStorageLifecyclePolicyReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetStorageLifecyclePolicyReferences'](arg1, arg2, arg3);
}

export function GetStorageLifecyclePolicyTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetStorageLifecyclePolicyTags'](arg1, arg2, arg3);
}

export function GetSystemRAMGB() {
  return window['go']['app']['App']['GetSystemRAMGB']();
}

export function GetTabSessionID(arg1) {
  return window['go']['app']['App']['GetTabSessionID'](arg1);
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function GetTableColumnsWithTypes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableColumnsWithTypes'](arg1, arg2, arg3);
}

export function GetTableForeignKeys(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableForeignKeys'](arg1, arg2, arg3);
}

export function GetTableRetentionDays(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableRetentionDays'](arg1, arg2, arg3);
}

export function GetTableSettings(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableSettings'](arg1, arg2, arg3);
}

export function GetTagReferences(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTagReferences'](arg1, arg2, arg3);
}

export function GetTaskRunHistory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetTaskRunHistory'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTaskStatuses(arg1, arg2) {
  return window['go']['app']['App']['GetTaskStatuses'](arg1, arg2);
}

export function GetTopologicalOrder(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTopologicalOrder'](arg1, arg2, arg3);
}

export function GetUserDDL(arg1) {
  return window['go']['app']['App']['GetUserDDL'](arg1);
}

export function GetWarehouseDDL(arg1) {
  return window['go']['app']['App']['GetWarehouseDDL'](arg1);
}

export function GetWarehouseMeteringHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetWarehouseMeteringHistory'](arg1, arg2, arg3);
}

export function GetWarehouseParameters(arg1) {
  return window['go']['app']['App']['GetWarehouseParameters'](arg1);
}

export function GitCancelOAuth() {
  return window['go']['app']['App']['GitCancelOAuth']();
}

export function GitCheckoutBranch(arg1, arg2) {
  return window['go']['app']['App']['GitCheckoutBranch'](arg1, arg2);
}

export function GitCheckoutRemoteBranch(arg1, arg2) {
  return window['go']['app']['App']['GitCheckoutRemoteBranch'](arg1, arg2);
}

export function GitClone(arg1) {
  return window['go']['app']['App']['GitClone'](arg1);
}

export function GitCommitAndPush(arg1) {
  return window['go']['app']['App']['GitCommitAndPush'](arg1);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['app']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitDeleteBranch(arg1, arg2) {
  return window['go']['app']['App']['GitDeleteBranch'](arg1, arg2);
}

export function GitDeleteRemoteBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitDeleteRemoteBranch'](arg1, arg2, arg3);
}

export function GitDiscardFile(arg1, arg2) {
  return window['go']['app']['App']['GitDiscardFile'](arg1, arg2);
}

export function GitFetch(arg1, arg2) {
  return window['go']['app']['App']['GitFetch'](arg1, arg2);
}

export function GitGetHeadFileContent(arg1) {
  return window['go']['app']['App']['GitGetHeadFileContent'](arg1);
}

export function GitInitWithRemote(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitInitWithRemote'](arg1, arg2, arg3);
}

export function GitListBranches(arg1) {
  return window['go']['app']['App']['GitListBranches'](arg1);
}

export function GitLoginWithOAuth(arg1) {
  return window['go']['app']['App']['GitLoginWithOAuth'](arg1);
}

export function GitLookupCredentials(arg1) {
  return window['go']['app']['App']['GitLookupCredentials'](arg1);
}

export function GitMergeBranch(arg1, arg2) {
  return window['go']['app']['App']['GitMergeBranch'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['app']['App']['GitPull'](arg1);
}

export function GitPushBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitPushBranch'](arg1, arg2, arg3);
}

export function GitResetHard(arg1) {
  return window['go']['app']['App']['GitResetHard'](arg1);
}

export function GitStageAll(arg1) {
  return window['go']['app']['App']['GitStageAll'](arg1);
}

export function GitStageFile(arg1, arg2) {
  return window['go']['app']['App']['GitStageFile'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['app']['App']['GitStatus'](arg1);
}

export function GitUnstageAll(arg1) {
  return window['go']['app']['App']['GitUnstageAll'](arg1);
}

export function GitUnstageFile(arg1, arg2) {
  return window['go']['app']['App']['GitUnstageFile'](arg1, arg2);
}

export function GitUpdateRemoteURL(arg1, arg2) {
  return window['go']['app']['App']['GitUpdateRemoteURL'](arg1, arg2);
}

export function HybridIndexColumnOptions(arg1) {
  return window['go']['app']['App']['HybridIndexColumnOptions'](arg1);
}

export function ImportTableData(arg1) {
  return window['go']['app']['App']['ImportTableData'](arg1);
}

export function InitTabSession(arg1) {
  return window['go']['app']['App']['InitTabSession'](arg1);
}

export function InstallCondaEnv() {
  return window['go']['app']['App']['InstallCondaEnv']();
}

export function InstallEnvPackage(arg1) {
  return window['go']['app']['App']['InstallEnvPackage'](arg1);
}

export function InstallJupyterNotebook() {
  return window['go']['app']['App']['InstallJupyterNotebook']();
}

export function InstallJupyterVenv() {
  return window['go']['app']['App']['InstallJupyterVenv']();
}

export function InstallPyprojectFile(arg1) {
  return window['go']['app']['App']['InstallPyprojectFile'](arg1);
}

export function InstallRequirementsFile(arg1) {
  return window['go']['app']['App']['InstallRequirementsFile'](arg1);
}

export function InstallSnowparkPackage() {
  return window['go']['app']['App']['InstallSnowparkPackage']();
}

export function InstallSnowparkVenv(arg1) {
  return window['go']['app']['App']['InstallSnowparkVenv'](arg1);
}

export function InstallVenvEnv() {
  return window['go']['app']['App']['InstallVenvEnv']();
}

export function IsAppleSilicon() {
  return window['go']['app']['App']['IsAppleSilicon']();
}

export function IsBoolean(arg1) {
  return window['go']['app']['App']['IsBoolean'](arg1);
}

export function IsConnected() {
  return window['go']['app']['App']['IsConnected']();
}

export function IsNumeric(arg1) {
  return window['go']['app']['App']['IsNumeric'](arg1);
}

export function IsQueryLogEnabled() {
  return window['go']['app']['App']['IsQueryLogEnabled']();
}

export function ListAIModels(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListAIModels'](arg1, arg2, arg3);
}

export function ListAccountMaskingPolicies() {
  return window['go']['app']['App']['ListAccountMaskingPolicies']();
}

export function ListAccountTags() {
  return window['go']['app']['App']['ListAccountTags']();
}

export function ListApiIntegrations() {
  return window['go']['app']['App']['ListApiIntegrations']();
}

export function ListAvailableRoles() {
  return window['go']['app']['App']['ListAvailableRoles']();
}

export function ListBackupPolicies() {
  return window['go']['app']['App']['ListBackupPolicies']();
}

export function ListBackupSets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListBackupSets'](arg1, arg2, arg3, arg4, arg5);
}

export function ListBackups(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListBackups'](arg1, arg2, arg3);
}

export function ListBasicObjects(arg1, arg2) {
  return window['go']['app']['App']['ListBasicObjects'](arg1, arg2);
}

export function ListComputePools() {
  return window['go']['app']['App']['ListComputePools']();
}

export function ListDatabases() {
  return window['go']['app']['App']['ListDatabases']();
}

export function ListDatasetVersions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListDatasetVersions'](arg1, arg2, arg3);
}

export function ListDbtProjectEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListDbtProjectEntries'](arg1, arg2, arg3, arg4);
}

export function ListDbtProjectVersions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListDbtProjectVersions'](arg1, arg2, arg3);
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ListDroppedDatabases() {
  return window['go']['app']['App']['ListDroppedDatabases']();
}

export function ListDroppedSchemas(arg1) {
  return window['go']['app']['App']['ListDroppedSchemas'](arg1);
}

export function ListDroppedTables(arg1, arg2) {
  return window['go']['app']['App']['ListDroppedTables'](arg1, arg2);
}

export function ListEnvPackages() {
  return window['go']['app']['App']['ListEnvPackages']();
}

export function ListExportableDatabases() {
  return window['go']['app']['App']['ListExportableDatabases']();
}

export function ListExternalAccessIntegrations() {
  return window['go']['app']['App']['ListExternalAccessIntegrations']();
}

export function ListExternalVolumes() {
  return window['go']['app']['App']['ListExternalVolumes']();
}

export function ListFileFormats(arg1, arg2) {
  return window['go']['app']['App']['ListFileFormats'](arg1, arg2);
}

export function ListFinalizableTasks(arg1, arg2) {
  return window['go']['app']['App']['ListFinalizableTasks'](arg1, arg2);
}

export function ListGitBranches(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListGitBranches'](arg1, arg2, arg3);
}

export function ListGitRepoEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListGitRepoEntries'](arg1, arg2, arg3, arg4);
}

export function ListGitTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListGitTags'](arg1, arg2, arg3);
}

export function ListHybridTableIndexes(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListHybridTableIndexes'](arg1, arg2, arg3);
}

export function ListImagesInRepository(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListImagesInRepository'](arg1, arg2, arg3);
}

export function ListIntegrations(arg1) {
  return window['go']['app']['App']['ListIntegrations'](arg1);
}

export function ListMCPSessions() {
  return window['go']['app']['App']['ListMCPSessions']();
}

export function ListModelVersions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListModelVersions'](arg1, arg2, arg3);
}

export function ListModels() {
  return window['go']['app']['App']['ListModels']();
}

export function ListNotificationIntegrations() {
  return window['go']['app']['App']['ListNotificationIntegrations']();
}

export function ListObjects(arg1, arg2) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2);
}

export function ListRoles() {
  return window['go']['app']['App']['ListRoles']();
}

export function ListRootTasks(arg1, arg2) {
  return window['go']['app']['App']['ListRootTasks'](arg1, arg2);
}

export function ListSchemas(arg1) {
  return window['go']['app']['App']['ListSchemas'](arg1);
}

export function ListSecretsInAccount() {
  return window['go']['app']['App']['ListSecretsInAccount']();
}

export function ListSecurityIntegrations() {
  return window['go']['app']['App']['ListSecurityIntegrations']();
}

export function ListSemanticDimensions(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListSemanticDimensions'](arg1, arg2, arg3);
}

export function ListSemanticDimensionsForMetric(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListSemanticDimensionsForMetric'](arg1, arg2, arg3, arg4);
}

export function ListSemanticFacts(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListSemanticFacts'](arg1, arg2, arg3);
}

export function ListSemanticMetrics(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListSemanticMetrics'](arg1, arg2, arg3);
}

export function ListServiceEndpoints(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListServiceEndpoints'](arg1, arg2, arg3);
}

export function ListStageEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListStageEntries'](arg1, arg2, arg3, arg4);
}

export function ListStageFiles(arg1, arg2) {
  return window['go']['app']['App']['ListStageFiles'](arg1, arg2);
}

export function ListStages(arg1, arg2) {
  return window['go']['app']['App']['ListStages'](arg1, arg2);
}

export function ListSupportedDbtVersions() {
  return window['go']['app']['App']['ListSupportedDbtVersions']();
}

export function ListSystemPythons() {
  return window['go']['app']['App']['ListSystemPythons']();
}

export function ListUserFunctions(arg1) {
  return window['go']['app']['App']['ListUserFunctions'](arg1);
}

export function ListUserSchemas(arg1) {
  return window['go']['app']['App']['ListUserSchemas'](arg1);
}

export function ListUsers() {
  return window['go']['app']['App']['ListUsers']();
}

export function ListWarehouses() {
  return window['go']['app']['App']['ListWarehouses']();
}

export function ListWorkspaceEntries(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListWorkspaceEntries'](arg1, arg2, arg3, arg4);
}

export function ListWorkspaces() {
  return window['go']['app']['App']['ListWorkspaces']();
}

export function LoadNotebookBreakpoints(arg1) {
  return window['go']['app']['App']['LoadNotebookBreakpoints'](arg1);
}

export function LoadSnowflakeCLIConfig() {
  return window['go']['app']['App']['LoadSnowflakeCLIConfig']();
}

export function MakeNotebookLive(arg1, arg2, arg3) {
  return window['go']['app']['App']['MakeNotebookLive'](arg1, arg2, arg3);
}

export function NeedsQuotes(arg1) {
  return window['go']['app']['App']['NeedsQuotes'](arg1);
}

export function NewNotebook() {
  return window['go']['app']['App']['NewNotebook']();
}

export function NormalizeSqlScalar(arg1) {
  return window['go']['app']['App']['NormalizeSqlScalar'](arg1);
}

export function NotebookUseContext(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['NotebookUseContext'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenFolderInNewInstance(arg1) {
  return window['go']['app']['App']['OpenFolderInNewInstance'](arg1);
}

export function ParseClientPolicy(arg1) {
  return window['go']['app']['App']['ParseClientPolicy'](arg1);
}

export function ParseMFAPolicy(arg1) {
  return window['go']['app']['App']['ParseMFAPolicy'](arg1);
}

export function ParsePATPolicy(arg1) {
  return window['go']['app']['App']['ParsePATPolicy'](arg1);
}

export function ParsePackagesPolicyList(arg1) {
  return window['go']['app']['App']['ParsePackagesPolicyList'](arg1);
}

export function ParseSecondaryRoles(arg1) {
  return window['go']['app']['App']['ParseSecondaryRoles'](arg1);
}

export function ParseSqlList(arg1) {
  return window['go']['app']['App']['ParseSqlList'](arg1);
}

export function ParseWorkloadIdentityPolicy(arg1) {
  return window['go']['app']['App']['ParseWorkloadIdentityPolicy'](arg1);
}

export function PickAnyFile() {
  return window['go']['app']['App']['PickAnyFile']();
}

export function PickCACertFile() {
  return window['go']['app']['App']['PickCACertFile']();
}

export function PickDataFile() {
  return window['go']['app']['App']['PickDataFile']();
}

export function PickDataFileByFormat(arg1) {
  return window['go']['app']['App']['PickDataFileByFormat'](arg1);
}

export function PickDataFilesByFormat(arg1) {
  return window['go']['app']['App']['PickDataFilesByFormat'](arg1);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function PickFileForFormatPreview() {
  return window['go']['app']['App']['PickFileForFormatPreview']();
}

export function PickFreezeOutputFile() {
  return window['go']['app']['App']['PickFreezeOutputFile']();
}

export function PickNotebookFile() {
  return window['go']['app']['App']['PickNotebookFile']();
}

export function PickOpenFile() {
  return window['go']['app']['App']['PickOpenFile']();
}

export function PickPyprojectFile() {
  return window['go']['app']['App']['PickPyprojectFile']();
}

export function PickQueryLogExportFile(arg1) {
  return window['go']['app']['App']['PickQueryLogExportFile'](arg1);
}

export function PickRequirementsFile() {
  return window['go']['app']['App']['PickRequirementsFile']();
}

export function PickSaveExportFile(arg1, arg2) {
  return window['go']['app']['App']['PickSaveExportFile'](arg1, arg2);
}

export function PickSaveFile(arg1) {
  return window['go']['app']['App']['PickSaveFile'](arg1);
}

export function PickSnowflakeCLIConfigPath() {
  return window['go']['app']['App']['PickSnowflakeCLIConfigPath']();
}

export function QuoteSqlText(arg1) {
  return window['go']['app']['App']['QuoteSqlText'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function ReadFileHead(arg1, arg2) {
  return window['go']['app']['App']['ReadFileHead'](arg1, arg2);
}

export function ReadNotebook(arg1) {
  return window['go']['app']['App']['ReadNotebook'](arg1);
}

export function ReconcileAllExclusiveList(arg1) {
  return window['go']['app']['App']['ReconcileAllExclusiveList'](arg1);
}

export function ReconcileSecondaryRoles(arg1) {
  return window['go']['app']['App']['ReconcileSecondaryRoles'](arg1);
}

export function RemoveEditorTab(arg1) {
  return window['go']['app']['App']['RemoveEditorTab'](arg1);
}

export function RemoveStageFiles(arg1, arg2) {
  return window['go']['app']['App']['RemoveStageFiles'](arg1, arg2);
}

export function RenameFile(arg1, arg2) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['app']['App']['RenameProfile'](arg1, arg2);
}

export function ResetPipRegistryConfig() {
  return window['go']['app']['App']['ResetPipRegistryConfig']();
}

export function ResizeShell(arg1, arg2) {
  return window['go']['app']['App']['ResizeShell'](arg1, arg2);
}

export function RestoreFromBackup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['RestoreFromBackup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ResumeTaskList(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResumeTaskList'](arg1, arg2, arg3);
}

export function RevealInFinder(arg1) {
  return window['go']['app']['App']['RevealInFinder'](arg1);
}

export function RunExplain(arg1, arg2) {
  return window['go']['app']['App']['RunExplain'](arg1, arg2);
}

export function RunNotebookCell(arg1, arg2, arg3) {
  return window['go']['app']['App']['RunNotebookCell'](arg1, arg2, arg3);
}

export function RunNotebookCellSql(arg1, arg2) {
  return window['go']['app']['App']['RunNotebookCellSql'](arg1, arg2);
}

export function RunNotebookSql(arg1) {
  return window['go']['app']['App']['RunNotebookSql'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['app']['App']['SaveAIConfig'](arg1);
}

export function SaveBinaryFile(arg1, arg2) {
  return window['go']['app']['App']['SaveBinaryFile'](arg1, arg2);
}

export function SaveEditorPrefs(arg1) {
  return window['go']['app']['App']['SaveEditorPrefs'](arg1);
}

export function SaveFeatureFlags(arg1) {
  return window['go']['app']['App']['SaveFeatureFlags'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['app']['App']['SaveFile'](arg1, arg2);
}

export function SaveGitConfig(arg1) {
  return window['go']['app']['App']['SaveGitConfig'](arg1);
}

export function SaveNotebook(arg1, arg2) {
  return window['go']['app']['App']['SaveNotebook'](arg1, arg2);
}

export function SaveNotebookBreakpoints(arg1, arg2) {
  return window['go']['app']['App']['SaveNotebookBreakpoints'](arg1, arg2);
}

export function SaveNotebookPrefs(arg1) {
  return window['go']['app']['App']['SaveNotebookPrefs'](arg1);
}

export function SavePipRegistryConfig(arg1) {
  return window['go']['app']['App']['SavePipRegistryConfig'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['app']['App']['SaveProfile'](arg1);
}

export function SaveSessionConfig(arg1) {
  return window['go']['app']['App']['SaveSessionConfig'](arg1);
}

export function SaveSnowparkConfig(arg1) {
  return window['go']['app']['App']['SaveSnowparkConfig'](arg1);
}

export function SaveSnowparkPythonPath(arg1) {
  return window['go']['app']['App']['SaveSnowparkPythonPath'](arg1);
}

export function SaveSnowparkVenvPath(arg1) {
  return window['go']['app']['App']['SaveSnowparkVenvPath'](arg1);
}

export function ScanMigrationSource(arg1) {
  return window['go']['app']['App']['ScanMigrationSource'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SetDefaultProfile(arg1) {
  return window['go']['app']['App']['SetDefaultProfile'](arg1);
}

export function SetGitCommitFilter(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetGitCommitFilter'](arg1, arg2, arg3, arg4);
}

export function SetNotebookQueryWarehouse(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetNotebookQueryWarehouse'](arg1, arg2, arg3, arg4);
}

export function SetObjectTag(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SetObjectTag'](arg1, arg2, arg3, arg4, arg5);
}

export function SetQueryLogEnabled(arg1) {
  return window['go']['app']['App']['SetQueryLogEnabled'](arg1);
}

export function SetSessionParameter(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetSessionParameter'](arg1, arg2, arg3);
}

export function SetSessionVariable(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetSessionVariable'](arg1, arg2, arg3);
}

export function SetUserPublicKey(arg1, arg2) {
  return window['go']['app']['App']['SetUserPublicKey'](arg1, arg2);
}

export function StartDapProxy() {
  return window['go']['app']['App']['StartDapProxy']();
}

export function StartFileWatcher(arg1) {
  return window['go']['app']['App']['StartFileWatcher'](arg1);
}

export function StartMCPSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StartMCPSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartNotebookSession(arg1) {
  return window['go']['app']['App']['StartNotebookSession'](arg1);
}

export function StartQuery(arg1, arg2) {
  return window['go']['app']['App']['StartQuery'](arg1, arg2);
}

export function StartShell(arg1, arg2) {
  return window['go']['app']['App']['StartShell'](arg1, arg2);
}

export function StopDapProxy() {
  return window['go']['app']['App']['StopDapProxy']();
}

export function StopFileWatcher() {
  return window['go']['app']['App']['StopFileWatcher']();
}

export function StopMCPSession(arg1) {
  return window['go']['app']['App']['StopMCPSession'](arg1);
}

export function StopNotebookSession(arg1) {
  return window['go']['app']['App']['StopNotebookSession'](arg1);
}

export function StopShell() {
  return window['go']['app']['App']['StopShell']();
}

export function SuspendTaskGraph(arg1, arg2, arg3) {
  return window['go']['app']['App']['SuspendTaskGraph'](arg1, arg2, arg3);
}

export function SuspendTaskList(arg1, arg2, arg3) {
  return window['go']['app']['App']['SuspendTaskList'](arg1, arg2, arg3);
}

export function TaskHasChildren(arg1, arg2, arg3) {
  return window['go']['app']['App']['TaskHasChildren'](arg1, arg2, arg3);
}

export function TestAIModel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['TestAIModel'](arg1, arg2, arg3, arg4, arg5);
}

export function UninstallEnvPackage(arg1) {
  return window['go']['app']['App']['UninstallEnvPackage'](arg1);
}

export function UnsetObjectTag(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UnsetObjectTag'](arg1, arg2, arg3, arg4);
}

export function UpdateERDesignerState(arg1, arg2) {
  return window['go']['app']['App']['UpdateERDesignerState'](arg1, arg2);
}

export function UpdateEditorContext(arg1, arg2) {
  return window['go']['app']['App']['UpdateEditorContext'](arg1, arg2);
}

export function UpdateEditorTabSQL(arg1, arg2) {
  return window['go']['app']['App']['UpdateEditorTabSQL'](arg1, arg2);
}

export function UpdateMCPSessionMode(arg1, arg2) {
  return window['go']['app']['App']['UpdateMCPSessionMode'](arg1, arg2);
}

export function UpdateQueryResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['UpdateQueryResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadFileToStage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['UploadFileToStage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UseDatabase(arg1, arg2) {
  return window['go']['app']['App']['UseDatabase'](arg1, arg2);
}

export function UseRole(arg1, arg2) {
  return window['go']['app']['App']['UseRole'](arg1, arg2);
}

export function UseSchema(arg1, arg2) {
  return window['go']['app']['App']['UseSchema'](arg1, arg2);
}

export function UseWarehouse(arg1, arg2) {
  return window['go']['app']['App']['UseWarehouse'](arg1, arg2);
}

export function VenvFolderExists() {
  return window['go']['app']['App']['VenvFolderExists']();
}

export function WaitForQueryResult(arg1) {
  return window['go']['app']['App']['WaitForQueryResult'](arg1);
}

export function WriteShell(arg1) {
  return window['go']['app']['App']['WriteShell'](arg1);
}
