// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {migration} from '../models';
import {authenticationpolicy} from '../models';
import {column} from '../models';
import {dbtproject} from '../models';
import {stage} from '../models';
import {integrations} from '../models';
import {procedure} from '../models';
import {agent} from '../models';
import {aggregationpolicy} from '../models';
import {alert} from '../models';
import {contact} from '../models';
import {cortexsearchservice} from '../models';
import {datametricfunction} from '../models';
import {dataset} from '../models';
import {dynamictable} from '../models';
import {eventtable} from '../models';
import {externalagent} from '../models';
import {externalfunction} from '../models';
import {externaltable} from '../models';
import {fileformat} from '../models';
import {udf} from '../models';
import {gateway} from '../models';
import {snowgitrepo} from '../models';
import {hybridtable} from '../models';
import {icebergtable} from '../models';
import {imagerepository} from '../models';
import {joinpolicy} from '../models';
import {mcpserver} from '../models';
import {maskingpolicy} from '../models';
import {materializedview} from '../models';
import {modelmonitor} from '../models';
import {model} from '../models';
import {networkrule} from '../models';
import {packagespolicy} from '../models';
import {passwordpolicy} from '../models';
import {pipe} from '../models';
import {privacypolicy} from '../models';
import {projectionpolicy} from '../models';
import {rowaccesspolicy} from '../models';
import {secret} from '../models';
import {semanticview} from '../models';
import {sequence} from '../models';
import {service} from '../models';
import {sessionpolicy} from '../models';
import {storagelifecyclepolicy} from '../models';
import {stream} from '../models';
import {streamlit} from '../models';
import {tag} from '../models';
import {view} from '../models';
import {erdesigner} from '../models';
import {snowpark} from '../models';
import {snowflake} from '../models';
import {dbt} from '../models';
import {ddl} from '../models';
import {tasks} from '../models';
import {keypair} from '../models';
import {config} from '../models';
import {fnmeta} from '../models';
import {app} from '../models';
import {table} from '../models';
import {queryhistory} from '../models';
import {querylog} from '../models';
import {queryprofile} from '../models';
import {warehouse} from '../models';
import {gitrepo} from '../models';
import {backup} from '../models';
import {filesystem} from '../models';
import {mcp} from '../models';
import {sfconfig} from '../models';

export function AddBackup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddRecentDir(arg1:string):Promise<Array<string>>;

export function AlterAgent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterAggregationPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterAlert(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterAuthenticationPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterBackupPolicy(arg1:string,arg2:string):Promise<void>;

export function AlterBackupSet(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterContact(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterCortexSearchService(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterDataMetricFunction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AlterDataset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterDynamicTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterEventTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterExternalAgent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterExternalFunction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AlterExternalTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterFunction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AlterGateway(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterHybridTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterIcebergTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterImageRepository(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterJoinPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterMaskingPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterMaterializedView(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterModel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterModelMonitor(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterNetworkRule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterPackagesPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterPasswordPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterPipe(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterPrivacyPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterProcedure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AlterProjectionPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterRowAccessPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterSemanticView(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterSequence(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterService(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterSessionPolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterStage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterStorageLifecyclePolicy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterStream(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterStreamlit(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterTableProperty(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AlterTag(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterView(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AlterWarehouseAbortAllQueries(arg1:string):Promise<void>;

export function AlterWarehouseProperty(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AlterWarehouseRename(arg1:string,arg2:string):Promise<void>;

export function AlterWarehouseResume(arg1:string):Promise<void>;

export function AlterWarehouseSuspend(arg1:string):Promise<void>;

export function AnalyzeMigration(arg1:Array<migration.MigrationObject>,arg2:string):Promise<Array<migration.MigrationDiffItem>>;

export function AuthenticationPolicyBagOptions():Promise<authenticationpolicy.BagParamOptions>;

export function AuthenticationPolicyClientDriverVersions():Promise<Array<authenticationpolicy.DriverVersionHint>>;

export function AuthenticationPolicyClientDrivers():Promise<Array<string>>;

export function AuthenticationPolicyListParams():Promise<Array<authenticationpolicy.ListParamMeta>>;

export function AuthenticationPolicyMFAEnrollmentOptions():Promise<Array<string>>;

export function BuildAddColumnSql(arg1:string,arg2:string,arg3:string,arg4:column.AddColumnConfig):Promise<string>;

export function BuildAddDbtProjectVersionSql(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function BuildAlterDbtProjectSetSql(arg1:string,arg2:string,arg3:string,arg4:dbtproject.AlterSetConfig,arg5:string,arg6:string,arg7:string,arg8:Array<string>):Promise<Array<string>>;

export function BuildAlterStageSql(arg1:stage.AlterStageConfig):Promise<string>;

export function BuildApiIntegrationPreviewSQL(arg1:integrations.ApiIntegrationParams):Promise<string>;

export function BuildCallStatement(arg1:string,arg2:string,arg3:string,arg4:Array<procedure.Argument>):Promise<string>;

export function BuildChangeColumnTypeSql(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function BuildClientPolicyValue(arg1:authenticationpolicy.ClientPolicy):Promise<string>;

export function BuildCreateAgentSql(arg1:string,arg2:string,arg3:agent.AgentConfig):Promise<string>;

export function BuildCreateAggregationPolicySql(arg1:string,arg2:string,arg3:aggregationpolicy.AggregationPolicyConfig):Promise<string>;

export function BuildCreateAlertSql(arg1:string,arg2:string,arg3:alert.AlertConfig):Promise<string>;

export function BuildCreateAuthenticationPolicySql(arg1:string,arg2:string,arg3:authenticationpolicy.AuthenticationPolicyConfig):Promise<string>;

export function BuildCreateContactSql(arg1:string,arg2:string,arg3:contact.ContactConfig):Promise<string>;

export function BuildCreateCortexSearchServiceSql(arg1:string,arg2:string,arg3:cortexsearchservice.CortexSearchServiceConfig):Promise<string>;

export function BuildCreateDataMetricFunctionSql(arg1:string,arg2:string,arg3:datametricfunction.DataMetricFunctionConfig):Promise<string>;

export function BuildCreateDatasetSql(arg1:string,arg2:string,arg3:dataset.DatasetConfig):Promise<string>;

export function BuildCreateDbtProjectSql(arg1:string,arg2:string,arg3:dbtproject.CreateConfig):Promise<string>;

export function BuildCreateDynamicTableSql(arg1:string,arg2:string,arg3:dynamictable.DynamicTableConfig):Promise<string>;

export function BuildCreateEventTableSql(arg1:string,arg2:string,arg3:eventtable.EventTableConfig):Promise<string>;

export function BuildCreateExternalAgentSql(arg1:string,arg2:string,arg3:externalagent.ExternalAgentConfig):Promise<string>;

export function BuildCreateExternalFunctionSql(arg1:string,arg2:string,arg3:externalfunction.ExternalFunctionConfig):Promise<string>;

export function BuildCreateExternalTableSql(arg1:string,arg2:string,arg3:externaltable.ExternalTableConfig):Promise<string>;

export function BuildCreateFileFormatSql(arg1:string,arg2:string,arg3:fileformat.FileFormatConfig):Promise<string>;

export function BuildCreateFunctionSql(arg1:string,arg2:string,arg3:udf.FunctionConfig):Promise<string>;

export function BuildCreateGatewaySql(arg1:string,arg2:string,arg3:gateway.GatewayConfig):Promise<string>;

export function BuildCreateGitRepositorySql(arg1:string,arg2:string,arg3:snowgitrepo.GitRepositoryConfig):Promise<string>;

export function BuildCreateHybridTableSql(arg1:string,arg2:string,arg3:hybridtable.HybridTableConfig):Promise<string>;

export function BuildCreateIcebergTableSql(arg1:string,arg2:string,arg3:icebergtable.IcebergTableConfig):Promise<string>;

export function BuildCreateImageRepositorySql(arg1:string,arg2:string,arg3:imagerepository.ImageRepositoryConfig):Promise<string>;

export function BuildCreateJoinPolicySql(arg1:string,arg2:string,arg3:joinpolicy.JoinPolicyConfig):Promise<string>;

export function BuildCreateMCPServerSql(arg1:string,arg2:string,arg3:mcpserver.MCPServerConfig):Promise<string>;

export function BuildCreateMaskingPolicySql(arg1:string,arg2:string,arg3:maskingpolicy.MaskingPolicyConfig):Promise<string>;

export function BuildCreateMaterializedViewSql(arg1:string,arg2:string,arg3:materializedview.MaterializedViewConfig):Promise<string>;

export function BuildCreateModelMonitorSql(arg1:string,arg2:string,arg3:modelmonitor.ModelMonitorConfig):Promise<string>;

export function BuildCreateModelSql(arg1:string,arg2:string,arg3:model.ModelConfig):Promise<string>;

export function BuildCreateNetworkRuleSql(arg1:string,arg2:string,arg3:networkrule.NetworkRuleConfig):Promise<string>;

export function BuildCreatePackagesPolicySql(arg1:string,arg2:string,arg3:packagespolicy.PackagesPolicyConfig):Promise<string>;

export function BuildCreatePasswordPolicySql(arg1:string,arg2:string,arg3:passwordpolicy.PasswordPolicyConfig):Promise<string>;

export function BuildCreatePipeSql(arg1:string,arg2:string,arg3:pipe.PipeConfig):Promise<string>;

export function BuildCreatePrivacyPolicySql(arg1:string,arg2:string,arg3:privacypolicy.PrivacyPolicyConfig):Promise<string>;

export function BuildCreateProcedureSql(arg1:string,arg2:string,arg3:procedure.ProcedureConfig):Promise<string>;

export function BuildCreateProjectionPolicySql(arg1:string,arg2:string,arg3:projectionpolicy.ProjectionPolicyConfig):Promise<string>;

export function BuildCreateRowAccessPolicySql(arg1:string,arg2:string,arg3:rowaccesspolicy.RowAccessPolicyConfig):Promise<string>;

export function BuildCreateSecretSql(arg1:string,arg2:string,arg3:secret.SecretConfig):Promise<string>;

export function BuildCreateSemanticViewSql(arg1:string,arg2:string,arg3:semanticview.SemanticViewConfig):Promise<string>;

export function BuildCreateSequenceSql(arg1:string,arg2:string,arg3:sequence.SequenceConfig):Promise<string>;

export function BuildCreateServiceSql(arg1:string,arg2:string,arg3:service.ServiceConfig):Promise<string>;

export function BuildCreateSessionPolicySql(arg1:string,arg2:string,arg3:sessionpolicy.SessionPolicyConfig):Promise<string>;

export function BuildCreateStageSql(arg1:stage.StageConfig):Promise<string>;

export function BuildCreateStorageLifecyclePolicySql(arg1:string,arg2:string,arg3:storagelifecyclepolicy.StorageLifecyclePolicyConfig):Promise<string>;

export function BuildCreateStreamSql(arg1:string,arg2:string,arg3:stream.StreamConfig):Promise<string>;

export function BuildCreateStreamlitSql(arg1:string,arg2:string,arg3:streamlit.StreamlitConfig):Promise<string>;

export function BuildCreateTagSql(arg1:string,arg2:string,arg3:tag.TagConfig):Promise<string>;

export function BuildCreateViewSql(arg1:string,arg2:string,arg3:view.ViewConfig):Promise<string>;

export function BuildDropColumnDefaultSql(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BuildDropColumnNotNullSql(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BuildDropColumnSql(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BuildExecuteDbtProjectSql(arg1:string,arg2:string,arg3:string,arg4:dbtproject.ExecuteConfig):Promise<string>;

export function BuildFunctionSelectStatement(arg1:string,arg2:string,arg3:string,arg4:Array<procedure.Argument>,arg5:boolean):Promise<string>;

export function BuildJoinSQL(arg1:erdesigner.JoinQueryState):Promise<string>;

export function BuildJoinState(arg1:erdesigner.JoinPath,arg2:Array<erdesigner.TableRef>,arg3:string):Promise<erdesigner.JoinQueryState>;

export function BuildMFAPolicyValue(arg1:authenticationpolicy.MFAPolicy):Promise<string>;

export function BuildModifyGitRepositorySql(arg1:string,arg2:string,arg3:string,arg4:snowgitrepo.GitRepositoryConfig,arg5:string,arg6:string,arg7:string):Promise<Array<string>>;

export function BuildModifySecretSql(arg1:string,arg2:string,arg3:string,arg4:secret.SecretConfig,arg5:string):Promise<Array<string>>;

export function BuildPATPolicyValue(arg1:authenticationpolicy.PATPolicy):Promise<string>;

export function BuildRefreshPipeSql(arg1:string,arg2:string,arg3:string,arg4:pipe.RefreshPipeConfig):Promise<string>;

export function BuildRenameColumnSql(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function BuildSetColumnCommentSql(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function BuildSetColumnDefaultSql(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function BuildSetColumnMaskingPolicySql(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function BuildSetColumnNotNullSql(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BuildUnsetColumnMaskingPolicySql(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BuildWorkloadIdentityPolicyValue(arg1:authenticationpolicy.WorkloadIdentityPolicy):Promise<string>;

export function CanCreateIntegration(arg1:string):Promise<boolean>;

export function CanCreateUsers(arg1:string):Promise<boolean>;

export function CanManageUsers(arg1:string):Promise<boolean>;

export function CanModifyUserAuth(arg1:string):Promise<boolean>;

export function CanViewWarehouseMeteringHistory():Promise<boolean>;

export function CancelConnect():Promise<void>;

export function CancelExport():Promise<void>;

export function CancelMigration():Promise<void>;

export function CancelQuery(arg1:string):Promise<void>;

export function CheckAvailableKeyTools():Promise<Array<string>>;

export function CheckPythonSyntax(arg1:string,arg2:string,arg3:string):Promise<Array<snowpark.NotebookSyntaxError>>;

export function CheckSnowparkEnv():Promise<snowpark.SnowparkCheckResult>;

export function ClearDefaultProfile():Promise<void>;

export function ClearERDesignerState():Promise<void>;

export function ClearObjectCache():Promise<void>;

export function ClearObjectCacheForDatabase(arg1:string):Promise<void>;

export function ClearQueryLog():Promise<void>;

export function ClearQueryResult(arg1:string):Promise<void>;

export function ClearRecentDirs():Promise<void>;

export function CloneChildTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:Array<string>):Promise<void>;

export function CloneProfile(arg1:string,arg2:string):Promise<void>;

export function CloseTabSession(arg1:string):Promise<void>;

export function Connect(arg1:snowflake.ConnectParams):Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<string>;

export function CreateApiIntegration(arg1:integrations.ApiIntegrationParams):Promise<void>;

export function CreateBackupPolicy(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:boolean):Promise<void>;

export function CreateBackupSet(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:boolean):Promise<void>;

export function CreateCatalogIntegration(arg1:integrations.CatalogIntegrationParams):Promise<void>;

export function CreateDbtProject(arg1:dbt.CreateRequest,arg2:Record<string, Array<string>>):Promise<dbt.CreateResult>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateExternalAccessIntegration(arg1:integrations.ExternalAccessIntegrationParams):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateHybridTableIndex(arg1:string,arg2:string,arg3:string,arg4:hybridtable.HybridIndex,arg5:boolean):Promise<void>;

export function CreateMigrationSnapshot(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string,arg7:boolean):Promise<void>;

export function CreateNotificationIntegration(arg1:integrations.NotificationIntegrationParams):Promise<void>;

export function CreateSecurityIntegration(arg1:integrations.SecurityIntegrationParams):Promise<void>;

export function CreateStorageIntegration(arg1:integrations.StorageIntegrationParams):Promise<void>;

export function DebugNotebookCell(arg1:string,arg2:string,arg3:string):Promise<snowpark.NotebookCellOutput>;

export function DeleteDirectory(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteOldestBackup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteVenvFolder():Promise<void>;

export function DeployNotebook(arg1:snowflake.DeployNotebookParams):Promise<void>;

export function DescribeAgent(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function DescribeAuthenticationPolicy(arg1:string,arg2:string,arg3:string):Promise<Array<snowflake.PropertyPair>>;

export function DescribeDataMetricFunction(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.QueryResult>;

export function DescribeDbtProject(arg1:string,arg2:string,arg3:string):Promise<Array<snowflake.PropertyPair>>;

export function DescribeExternalFunction(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.QueryResult>;

export function DescribeGateway(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function DescribeMCPServer(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function DescribePasswordPolicy(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function DescribeSemanticView(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function DescribeSessionPolicy(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function Disconnect():Promise<void>;

export function DownloadFileFromStage(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function DropBackupPolicy(arg1:string):Promise<void>;

export function DropBackupSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DropDatabase(arg1:string,arg2:string):Promise<void>;

export function DropHybridTableIndex(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropIntegration(arg1:string):Promise<void>;

export function DropSchema(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DropTaskTree(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DuplicateFile(arg1:string):Promise<string>;

export function EnableTaskDependents(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecDDL(arg1:string):Promise<void>;

export function ExecuteAlert(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteGitFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecuteMigration(arg1:Array<migration.MigrationObject>,arg2:string,arg3:number,arg4:migration.TableMigrationStrategy):Promise<Array<migration.MigrationExecEvent>>;

export function ExecuteNotebook(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function ExecuteQuery(arg1:string):Promise<snowflake.QueryResult>;

export function ExecuteStageFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecuteTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ExportAccountObjectsDDL(arg1:string):Promise<ddl.AccountExportResult>;

export function ExportAllDatabasesDDL(arg1:string,arg2:Array<string>):Promise<Array<ddl.ExportResult>>;

export function ExportDatabaseDDL(arg1:string,arg2:string):Promise<ddl.ExportResult>;

export function ExportGraphDDL(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<tasks.ExportGraphDDLResult>;

export function ExportTableData(arg1:snowflake.ExportTableParams):Promise<snowflake.ExportTableResult>;

export function FetchNotebookContent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FindJoinPaths(arg1:Array<erdesigner.TableRef>,arg2:Array<snowflake.ERForeignKey>):Promise<Array<erdesigner.JoinPath>>;

export function FormatAuthPolicyList(arg1:Array<string>):Promise<string>;

export function FormatContactUsers(arg1:Array<string>):Promise<string>;

export function FormatCortexSearchAttributes(arg1:Array<string>):Promise<string>;

export function FormatPackagesPolicyList(arg1:Array<string>):Promise<string>;

export function FormatSecondaryRoles(arg1:Array<string>):Promise<string>;

export function FreezeRequirements(arg1:string):Promise<void>;

export function GenerateKeyPair(arg1:string,arg2:string,arg3:string):Promise<keypair.KeyPairResult>;

export function GenerateMigrationScript(arg1:Array<migration.MigrationDiffItem>,arg2:string,arg3:migration.TableMigrationStrategy):Promise<string>;

export function GetAIConfig():Promise<config.AIConfig>;

export function GetAISuggestion(arg1:string):Promise<string>;

export function GetAdminLockedFlags():Promise<config.FeatureFlags>;

export function GetAggregationPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetAllFunctionNames():Promise<Array<fnmeta.FunctionMeta>>;

export function GetAllTagReferences():Promise<snowflake.QueryResult>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetAuthenticationPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetClientVersionInfo():Promise<Array<snowflake.ClientVersionInfo>>;

export function GetCollationLocales():Promise<Array<snowflake.CollationLocale>>;

export function GetCollationSpecifiers():Promise<Array<snowflake.CollationSpecifier>>;

export function GetCollations():Promise<Array<snowflake.CollationOption>>;

export function GetColumnDetails(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.ColumnDetails>;

export function GetColumnTagReferences(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.QueryResult>;

export function GetCortexSearchServiceTags(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetCurrentRegion():Promise<string>;

export function GetCurrentUser():Promise<string>;

export function GetDataMetricFunctionReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetDataMetricFunctionTags(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.QueryResult>;

export function GetDatabaseCrossDeps(arg1:string,arg2:Array<string>):Promise<Array<snowflake.SchemaRef>>;

export function GetDatabaseRetentionDays(arg1:string):Promise<number>;

export function GetDatabaseTableSummary(arg1:string):Promise<Array<table.TableSummary>>;

export function GetDefaultSessionConfig():Promise<config.SessionConfig>;

export function GetERDiagramData(arg1:string):Promise<snowflake.ERDiagramData>;

export function GetEditorPrefs():Promise<config.EditorPrefs>;

export function GetEventTableParameters(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetExternalFunctionOptions():Promise<externalfunction.BuilderOptions>;

export function GetFeatureFlags():Promise<config.FeatureFlags>;

export function GetFunctionInfo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.FunctionInfo>;

export function GetFunctionSuggestions(arg1:string):Promise<Array<fnmeta.FunctionMeta>>;

export function GetFunctionTooltip(arg1:string):Promise<Array<fnmeta.FunctionMeta>>;

export function GetGitCommitFilter(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetGitConfig():Promise<config.GitConfig>;

export function GetGitFileContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetIntegrationProperties(arg1:string):Promise<Array<snowflake.PropertyPair>>;

export function GetJoinPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetJoinPolicyTags(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetKernelPythonVersion(arg1:string):Promise<string>;

export function GetLocalFilePreview(arg1:string,arg2:fileformat.FileFormatConfig):Promise<fileformat.PreviewResult>;

export function GetMCPSessionConfig(arg1:string):Promise<string>;

export function GetMaskingPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetModelTags(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetNotebookCompletions(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<snowpark.NotebookCompletion>>;

export function GetNotebookHover(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function GetNotebookPrefs():Promise<config.NotebookPrefs>;

export function GetNotebookQueryWarehouse(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetObjectDDL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetObjectDependencies(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<snowflake.DependencyNode>;

export function GetObjectProperties(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<snowflake.PropertyPair>>;

export function GetObjectTagReferences(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<snowflake.QueryResult>;

export function GetPasswordPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetPipRegistryConfig():Promise<config.PipRegistryConfig>;

export function GetPipeCopyHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<snowflake.QueryResult>;

export function GetPipeStatus(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPlatformOS():Promise<string>;

export function GetPrivacyPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetPrivacyPolicyTags(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetProcedureParams(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<snowflake.ProcParam>>;

export function GetProjectionPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetQueryHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:boolean):Promise<Array<queryhistory.QueryHistoryRow>>;

export function GetQueryLogEntries():Promise<Array<querylog.Entry>>;

export function GetQueryOperatorStats(arg1:string):Promise<Array<queryprofile.OperatorStat>>;

export function GetQuotedIdentifiersIgnoreCase():Promise<boolean>;

export function GetRoleDDL(arg1:string):Promise<string>;

export function GetRoutineProperties(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<snowflake.PropertyPair>>;

export function GetRowAccessPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetSchemaCrossDeps(arg1:string,arg2:string):Promise<Array<snowflake.SchemaRef>>;

export function GetSchemaForeignKeys(arg1:string,arg2:string):Promise<Array<snowflake.TableForeignKey>>;

export function GetSchemaRetentionDays(arg1:string,arg2:string):Promise<number>;

export function GetSemanticViewTags(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetServiceContainers(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetServiceLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<string>;

export function GetSessionConfig():Promise<config.SessionConfig>;

export function GetSessionContext(arg1:string):Promise<snowflake.SessionContext>;

export function GetSessionInitMode():Promise<string>;

export function GetSessionParameters():Promise<Array<snowflake.SessionParam>>;

export function GetSessionPolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetSessionVariables():Promise<Array<snowflake.SessionVar>>;

export function GetSnowflakeCLIConfigPath():Promise<string>;

export function GetSnowparkConfig():Promise<snowpark.SnowparkConfigResult>;

export function GetSnowsightURL():Promise<string>;

export function GetStageFilePreview(arg1:string,arg2:fileformat.FileFormatConfig):Promise<fileformat.PreviewResult>;

export function GetStorageLifecyclePolicyReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetStorageLifecyclePolicyTags(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetSystemRAMGB():Promise<number>;

export function GetTabSessionID(arg1:string):Promise<string>;

export function GetTableColumns(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetTableColumnsWithTypes(arg1:string,arg2:string,arg3:string):Promise<Array<snowflake.ColumnInfo>>;

export function GetTableForeignKeys(arg1:string,arg2:string,arg3:string):Promise<Array<snowflake.TableForeignKey>>;

export function GetTableRetentionDays(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetTableSettings(arg1:string,arg2:string,arg3:string):Promise<table.TableSettings>;

export function GetTagReferences(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function GetTaskRunHistory(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<Array<tasks.TaskHistoryRow>>;

export function GetTaskStatuses(arg1:string,arg2:string):Promise<tasks.StatusesResult>;

export function GetTopologicalOrder(arg1:string,arg2:string,arg3:string):Promise<tasks.TopologicalOrder>;

export function GetUserDDL(arg1:string):Promise<string>;

export function GetWarehouseDDL(arg1:string):Promise<string>;

export function GetWarehouseMeteringHistory(arg1:string,arg2:string,arg3:string):Promise<Array<warehouse.WarehouseMeteringRow>>;

export function GetWarehouseParameters(arg1:string):Promise<Array<snowflake.PropertyPair>>;

export function GitCancelOAuth():Promise<void>;

export function GitCheckoutBranch(arg1:string,arg2:string):Promise<void>;

export function GitCheckoutRemoteBranch(arg1:string,arg2:string):Promise<void>;

export function GitClone(arg1:gitrepo.CloneParams):Promise<void>;

export function GitCommitAndPush(arg1:gitrepo.PushParams):Promise<void>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<void>;

export function GitDeleteBranch(arg1:string,arg2:string):Promise<void>;

export function GitDeleteRemoteBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitDiscardFile(arg1:string,arg2:string):Promise<void>;

export function GitFetch(arg1:string,arg2:string):Promise<void>;

export function GitGetHeadFileContent(arg1:string):Promise<string>;

export function GitInitWithRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitListBranches(arg1:string):Promise<Array<gitrepo.BranchInfo>>;

export function GitLoginWithOAuth(arg1:string):Promise<string>;

export function GitLookupCredentials(arg1:string):Promise<gitrepo.CredentialResult>;

export function GitMergeBranch(arg1:string,arg2:string):Promise<void>;

export function GitPull(arg1:gitrepo.PullParams):Promise<void>;

export function GitPushBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitResetHard(arg1:string):Promise<void>;

export function GitStageAll(arg1:string):Promise<void>;

export function GitStageFile(arg1:string,arg2:string):Promise<void>;

export function GitStatus(arg1:string):Promise<gitrepo.RepoStatus>;

export function GitUnstageAll(arg1:string):Promise<void>;

export function GitUnstageFile(arg1:string,arg2:string):Promise<void>;

export function GitUpdateRemoteURL(arg1:string,arg2:string):Promise<void>;

export function HybridIndexColumnOptions(arg1:Array<hybridtable.IndexColumn>):Promise<hybridtable.IndexColumnOptions>;

export function ImportTableData(arg1:snowflake.ImportTableParams):Promise<snowflake.ImportTableResult>;

export function InitTabSession(arg1:string):Promise<void>;

export function InstallCondaEnv():Promise<void>;

export function InstallEnvPackage(arg1:string):Promise<void>;

export function InstallJupyterNotebook():Promise<void>;

export function InstallJupyterVenv():Promise<void>;

export function InstallPyprojectFile(arg1:string):Promise<void>;

export function InstallRequirementsFile(arg1:string):Promise<void>;

export function InstallSnowparkPackage():Promise<void>;

export function InstallSnowparkVenv(arg1:boolean):Promise<void>;

export function InstallVenvEnv():Promise<void>;

export function IsAppleSilicon():Promise<boolean>;

export function IsBoolean(arg1:string):Promise<boolean>;

export function IsConnected():Promise<boolean>;

export function IsNumeric(arg1:string):Promise<boolean>;

export function IsQueryLogEnabled():Promise<boolean>;

export function ListAIModels(arg1:string,arg2:string,arg3:number):Promise<Array<string>>;

export function ListAccountMaskingPolicies():Promise<snowflake.QueryResult>;

export function ListAccountTags():Promise<snowflake.QueryResult>;

export function ListApiIntegrations():Promise<Array<snowflake.ApiIntegration>>;

export function ListAvailableRoles():Promise<Array<string>>;

export function ListBackupPolicies():Promise<Array<backup.BackupPolicyRow>>;

export function ListBackupSets(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<backup.BackupSetRow>>;

export function ListBackups(arg1:string,arg2:string,arg3:string):Promise<Array<backup.BackupRow>>;

export function ListBasicObjects(arg1:string,arg2:string):Promise<Array<snowflake.SnowflakeObject>>;

export function ListComputePools():Promise<Array<string>>;

export function ListDatabases():Promise<Array<string>>;

export function ListDatasetVersions(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListDbtProjectEntries(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<snowflake.GitRepoEntry>>;

export function ListDbtProjectVersions(arg1:string,arg2:string,arg3:string):Promise<Array<snowflake.DbtProjectVersion>>;

export function ListDirectory(arg1:string):Promise<Array<filesystem.FileEntry>>;

export function ListDroppedDatabases():Promise<Array<snowflake.DroppedTable>>;

export function ListDroppedSchemas(arg1:string):Promise<Array<snowflake.DroppedTable>>;

export function ListDroppedTables(arg1:string,arg2:string):Promise<Array<snowflake.DroppedTable>>;

export function ListEnvPackages():Promise<Array<snowpark.PackageInfo>>;

export function ListExportableDatabases():Promise<Array<string>>;

export function ListExternalAccessIntegrations():Promise<Array<snowflake.IntegrationRow>>;

export function ListExternalVolumes():Promise<Array<string>>;

export function ListFileFormats(arg1:string,arg2:string):Promise<Array<string>>;

export function ListFinalizableTasks(arg1:string,arg2:string):Promise<Array<tasks.FinalizabilityRow>>;

export function ListGitBranches(arg1:string,arg2:string,arg3:string):Promise<Array<snowflake.GitBranch>>;

export function ListGitRepoEntries(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<snowflake.GitRepoEntry>>;

export function ListGitTags(arg1:string,arg2:string,arg3:string):Promise<Array<snowflake.GitTag>>;

export function ListHybridTableIndexes(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListImagesInRepository(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListIntegrations(arg1:string):Promise<Array<snowflake.IntegrationRow>>;

export function ListMCPSessions():Promise<Array<mcp.SessionInfo>>;

export function ListModelVersions(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListModels():Promise<Array<string>>;

export function ListNotificationIntegrations():Promise<Array<string>>;

export function ListObjects(arg1:string,arg2:string):Promise<Array<snowflake.SnowflakeObject>>;

export function ListRoles():Promise<Array<string>>;

export function ListRootTasks(arg1:string,arg2:string):Promise<Array<tasks.FinalizabilityRow>>;

export function ListSchemas(arg1:string):Promise<Array<string>>;

export function ListSecretsInAccount():Promise<Array<snowflake.AccountSecret>>;

export function ListSecurityIntegrations():Promise<Array<snowflake.SecurityIntegration>>;

export function ListSemanticDimensions(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListSemanticDimensionsForMetric(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.QueryResult>;

export function ListSemanticFacts(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListSemanticMetrics(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListServiceEndpoints(arg1:string,arg2:string,arg3:string):Promise<snowflake.QueryResult>;

export function ListStageEntries(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<snowflake.GitRepoEntry>>;

export function ListStageFiles(arg1:string,arg2:string):Promise<Array<stage.StageFile>>;

export function ListStages(arg1:string,arg2:string):Promise<Array<snowflake.StageSummary>>;

export function ListSupportedDbtVersions():Promise<Array<dbtproject.DbtVersionInfo>>;

export function ListSystemPythons():Promise<Array<snowpark.PythonInfo>>;

export function ListUserFunctions(arg1:string):Promise<Array<snowflake.UserFunction>>;

export function ListUserSchemas(arg1:string):Promise<Array<string>>;

export function ListUsers():Promise<Array<snowflake.SnowflakeUser>>;

export function ListWarehouses():Promise<Array<string>>;

export function ListWorkspaceEntries(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<snowflake.GitRepoEntry>>;

export function ListWorkspaces():Promise<Array<snowflake.WorkspaceInfo>>;

export function LoadNotebookBreakpoints(arg1:string):Promise<Record<string, Array<number>>>;

export function LoadSnowflakeCLIConfig():Promise<sfconfig.Config>;

export function MakeNotebookLive(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NeedsQuotes(arg1:string):Promise<boolean>;

export function NewNotebook():Promise<string>;

export function NormalizeSqlScalar(arg1:string):Promise<string>;

export function NotebookUseContext(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function OpenFolderInNewInstance(arg1:string):Promise<void>;

export function ParseClientPolicy(arg1:string):Promise<authenticationpolicy.ClientPolicy>;

export function ParseMFAPolicy(arg1:string):Promise<authenticationpolicy.MFAPolicy>;

export function ParsePATPolicy(arg1:string):Promise<authenticationpolicy.PATPolicy>;

export function ParsePackagesPolicyList(arg1:string):Promise<Array<string>>;

export function ParseSecondaryRoles(arg1:string):Promise<Array<string>>;

export function ParseSqlList(arg1:string):Promise<Array<string>>;

export function ParseWorkloadIdentityPolicy(arg1:string):Promise<authenticationpolicy.WorkloadIdentityPolicy>;

export function PickAnyFile():Promise<string>;

export function PickCACertFile():Promise<string>;

export function PickDataFile():Promise<string>;

export function PickDataFileByFormat(arg1:string):Promise<string>;

export function PickDataFilesByFormat(arg1:string):Promise<Array<string>>;

export function PickDirectory():Promise<string>;

export function PickFileForFormatPreview():Promise<string>;

export function PickFreezeOutputFile():Promise<string>;

export function PickNotebookFile():Promise<string>;

export function PickOpenFile():Promise<string>;

export function PickPyprojectFile():Promise<string>;

export function PickQueryLogExportFile(arg1:string):Promise<string>;

export function PickRequirementsFile():Promise<string>;

export function PickSaveExportFile(arg1:string,arg2:string):Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function PickSnowflakeCLIConfigPath():Promise<string>;

export function QuoteSqlText(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileHead(arg1:string,arg2:number):Promise<string>;

export function ReadNotebook(arg1:string):Promise<string>;

export function ReconcileAllExclusiveList(arg1:Array<string>):Promise<Array<string>>;

export function ReconcileSecondaryRoles(arg1:Array<string>):Promise<Array<string>>;

export function RemoveEditorTab(arg1:string):Promise<void>;

export function RemoveStageFiles(arg1:string,arg2:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ResetPipRegistryConfig():Promise<void>;

export function ResizeShell(arg1:number,arg2:number):Promise<void>;

export function RestoreFromBackup(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function ResumeTaskList(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function RunExplain(arg1:string,arg2:string):Promise<queryprofile.ExplainResult>;

export function RunNotebookCell(arg1:string,arg2:string,arg3:string):Promise<snowpark.NotebookCellOutput>;

export function RunNotebookCellSql(arg1:string,arg2:string):Promise<snowpark.NotebookSqlResult>;

export function RunNotebookSql(arg1:string):Promise<snowpark.NotebookSqlResult>;

export function SaveAIConfig(arg1:config.AIConfig):Promise<void>;

export function SaveBinaryFile(arg1:string,arg2:string):Promise<void>;

export function SaveEditorPrefs(arg1:config.EditorPrefs):Promise<void>;

export function SaveFeatureFlags(arg1:config.FeatureFlags):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveGitConfig(arg1:config.GitConfig):Promise<void>;

export function SaveNotebook(arg1:string,arg2:string):Promise<void>;

export function SaveNotebookBreakpoints(arg1:string,arg2:Record<string, Array<number>>):Promise<void>;

export function SaveNotebookPrefs(arg1:config.NotebookPrefs):Promise<void>;

export function SavePipRegistryConfig(arg1:config.PipRegistryConfig):Promise<void>;

export function SaveProfile(arg1:sfconfig.Connection):Promise<void>;

export function SaveSessionConfig(arg1:config.SessionConfig):Promise<void>;

export function SaveSnowparkConfig(arg1:string):Promise<void>;

export function SaveSnowparkPythonPath(arg1:string):Promise<void>;

export function SaveSnowparkVenvPath(arg1:string):Promise<void>;

export function ScanMigrationSource(arg1:string):Promise<Array<migration.MigrationObject>>;

export function SearchFiles(arg1:string,arg2:string,arg3:boolean):Promise<Array<filesystem.SearchMatch>>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SetGitCommitFilter(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetNotebookQueryWarehouse(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetObjectTag(arg1:tag.ObjectTagRef,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetQueryLogEnabled(arg1:boolean):Promise<void>;

export function SetSessionParameter(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSessionVariable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetUserPublicKey(arg1:string,arg2:string):Promise<void>;

export function StartDapProxy():Promise<void>;

export function StartFileWatcher(arg1:string):Promise<void>;

export function StartMCPSession(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<mcp.SessionInfo>;

export function StartNotebookSession(arg1:string):Promise<void>;

export function StartQuery(arg1:string,arg2:string):Promise<string>;

export function StartShell(arg1:string,arg2:string):Promise<void>;

export function StopDapProxy():Promise<void>;

export function StopFileWatcher():Promise<void>;

export function StopMCPSession(arg1:string):Promise<void>;

export function StopNotebookSession(arg1:string):Promise<void>;

export function StopShell():Promise<void>;

export function SuspendTaskGraph(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SuspendTaskList(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function TaskHasChildren(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function TestAIModel(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function UninstallEnvPackage(arg1:string):Promise<void>;

export function UnsetObjectTag(arg1:tag.ObjectTagRef,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateERDesignerState(arg1:string,arg2:Array<mcp.ERDesignerTableOut>):Promise<void>;

export function UpdateEditorContext(arg1:string,arg2:string):Promise<void>;

export function UpdateEditorTabSQL(arg1:string,arg2:string):Promise<void>;

export function UpdateMCPSessionMode(arg1:string,arg2:string):Promise<mcp.SessionInfo>;

export function UpdateQueryResult(arg1:string,arg2:Array<string>,arg3:number,arg4:boolean,arg5:Array<any>,arg6:string):Promise<void>;

export function UploadFileToStage(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:string,arg6:boolean):Promise<void>;

export function UseDatabase(arg1:string,arg2:string):Promise<void>;

export function UseRole(arg1:string,arg2:string):Promise<void>;

export function UseSchema(arg1:string,arg2:string):Promise<void>;

export function UseWarehouse(arg1:string,arg2:string):Promise<void>;

export function VenvFolderExists():Promise<boolean>;

export function WaitForQueryResult(arg1:string):Promise<snowflake.QueryResult>;

export function WriteShell(arg1:string):Promise<void>;
