//go:build ignore

// gen_datatypes regenerates the frontend's Snowflake data-type catalogue from
// the authoritative Go registry (internal/snowflake/datatypes.go).
//
// The backend registry (snowflake.AllDataTypes) is the single source of truth
// for the type list, including param hints and categories.  The Monaco SQL
// tokenizer and the ER designer consume the list synchronously at module-load
// time (the tokenizer language object is registered with @datatypes resolved up
// front; the ER types feed module-level Sets and pure functions).  Routing
// those through the async GetAllDataTypes IPC — as the editor's autocomplete
// already does — would mean deferring/re-registering the language and threading
// Promises through otherwise-synchronous code, so a committed static artifact is
// the simpler way to keep the list in exactly one place.  TestGeneratedDataTypesInSync
// guards against drift.
//
// Usage:
//
//	go generate ./internal/snowflake/
//	go run scripts/gen_datatypes.go     (from any directory inside the project)
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"thaw/internal/snowflake"
)

func main() {
	root, err := findProjectRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	buf.WriteString("// Copyright (c) 2026 Technarion Oy. All rights reserved.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Code generated by scripts/gen_datatypes.go; DO NOT EDIT.\n")
	buf.WriteString("// Source of truth: internal/snowflake/datatypes.go (snowflake.AllDataTypes).\n")
	buf.WriteString("// Regenerate with: go generate ./internal/snowflake/\n")
	buf.WriteString("\n")
	buf.WriteString("/** A single Snowflake data type: canonical name + optional parameter hint. */\n")
	buf.WriteString("export interface SnowflakeDataType {\n")
	buf.WriteString("  name: string;\n")
	buf.WriteString("  paramHint: string;\n")
	buf.WriteString("  category: string;\n")
	buf.WriteString("}\n\n")
	buf.WriteString("/** The complete Snowflake data type catalogue, mirroring the Go registry. */\n")
	buf.WriteString("export const SNOWFLAKE_DATA_TYPES: readonly SnowflakeDataType[] = [\n")
	for _, dt := range snowflake.AllDataTypes() {
		fmt.Fprintf(&buf, "  { name: %q, paramHint: %q, category: %q },\n", dt.Name, dt.ParamHint, string(dt.Category))
	}
	buf.WriteString("];\n\n")
	buf.WriteString("/** Flat list of canonical data type names. */\n")
	buf.WriteString("export const SNOWFLAKE_DATA_TYPE_NAMES: readonly string[] =\n")
	buf.WriteString("  SNOWFLAKE_DATA_TYPES.map((dt) => dt.name);\n")

	outPath := filepath.Join(root, "frontend", "src", "generated", "snowflakeDataTypes.ts")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating output dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d types)\n", outPath, len(snowflake.AllDataTypes()))
}

// findProjectRoot walks parent directories until it finds go.mod.
func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found in any parent directory")
		}
		dir = parent
	}
}
