//go:build ignore

// gen_object_kinds regenerates the frontend's Snowflake object-kind catalogue
// from the authoritative Go registry (internal/objectkind).
//
// The registry is the single source of truth for the canonical KIND string, its
// display label, the tree/filter ordering and whether GET_DDL supports the kind.
// The sidebar consumes all of that synchronously while building the tree (label
// lookups and order comparisons happen per node, and the DDL guard runs while
// assembling a context menu), so routing it through an async IPC call would mean
// threading Promises through otherwise-synchronous render code. A committed
// static artifact keeps the data in exactly one place instead;
// TestGeneratedObjectKindsInSync guards against drift.
//
// Icons and colors stay hand-maintained in
// frontend/src/components/sidebar/objectIcons.tsx (they are React components);
// objectIcons.test.ts fails when a generated kind has no icon or color.
//
// Usage:
//
//	go generate ./internal/objectkind/
//	go run scripts/gen_object_kinds.go     (from any directory inside the project)
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"thaw/internal/objectkind"
)

func main() {
	root, err := findProjectRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	buf.WriteString("// SPDX-License-Identifier: GPL-3.0-or-later\n")
	buf.WriteString("//\n")
	buf.WriteString("// Code generated by scripts/gen_object_kinds.go; DO NOT EDIT.\n")
	buf.WriteString("// Source of truth: internal/objectkind/kinds.go (objectkind.Kinds).\n")
	buf.WriteString("// Regenerate with: go generate ./internal/objectkind/\n")
	buf.WriteString("\n")
	buf.WriteString("/** One Snowflake object kind, mirroring the Go registry entry. */\n")
	buf.WriteString("export interface SnowflakeObjectKind {\n")
	buf.WriteString("  /** Canonical KIND string, as it appears on objects returned by the backend. */\n")
	buf.WriteString("  name: string;\n")
	buf.WriteString("  /** Pluralised display label for the tree group and the search type filter. */\n")
	buf.WriteString("  label: string;\n")
	buf.WriteString("  /** True for the kinds SHOW OBJECTS returns directly (TABLE / VIEW / SEQUENCE). */\n")
	buf.WriteString("  basic: boolean;\n")
	buf.WriteString("  /** False when GET_DDL has no object type for the kind (no DDL / View Definition / comparison). */\n")
	buf.WriteString("  ddl: boolean;\n")
	buf.WriteString("}\n\n")
	buf.WriteString("/** Every object kind the object browser supports, in canonical display order. */\n")
	buf.WriteString("export const OBJECT_KINDS: readonly SnowflakeObjectKind[] = [\n")
	for _, k := range objectkind.Kinds {
		fmt.Fprintf(&buf, "  { name: %q, label: %q, basic: %t, ddl: %t },\n",
			k.Name, k.Label, k.Basic, k.GetDDLType != "")
	}
	buf.WriteString("];\n\n")
	buf.WriteString("/** Canonical kind order: tree grouping, search grouping, and the type-filter options. */\n")
	buf.WriteString("export const OBJECT_KIND_ORDER: readonly string[] = OBJECT_KINDS.map((k) => k.name);\n\n")
	buf.WriteString("/** Kind → pluralised display label. Unknown kinds have no entry; fall back to the raw kind. */\n")
	buf.WriteString("export const OBJECT_KIND_LABEL: Readonly<Record<string, string>> = Object.fromEntries(\n")
	buf.WriteString("  OBJECT_KINDS.map((k) => [k.name, k.label]),\n")
	buf.WriteString(");\n\n")
	buf.WriteString("/** Kinds Snowflake's GET_DDL cannot render — every DDL entry point must skip them. */\n")
	buf.WriteString("export const DDL_UNSUPPORTED_KINDS: ReadonlySet<string> = new Set(\n")
	buf.WriteString("  OBJECT_KINDS.filter((k) => !k.ddl).map((k) => k.name),\n")
	buf.WriteString(");\n")

	outPath := filepath.Join(root, "frontend", "src", "generated", "objectKinds.ts")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating output dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d kinds)\n", outPath, len(objectkind.Kinds))
}

// findProjectRoot walks parent directories until it finds go.mod.
func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found in any parent directory")
		}
		dir = parent
	}
}
