// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBackup'](arg1, arg2, arg3);
}

export function AlterBackupPolicy(arg1, arg2) {
  return window['go']['main']['App']['AlterBackupPolicy'](arg1, arg2);
}

export function AlterBackupSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AlterBackupSet'](arg1, arg2, arg3, arg4);
}

export function AlterTableProperty(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AlterTableProperty'](arg1, arg2, arg3, arg4, arg5);
}

export function AlterTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AlterTask'](arg1, arg2, arg3, arg4);
}

export function AlterWarehouseAbortAllQueries(arg1) {
  return window['go']['main']['App']['AlterWarehouseAbortAllQueries'](arg1);
}

export function AlterWarehouseProperty(arg1, arg2, arg3) {
  return window['go']['main']['App']['AlterWarehouseProperty'](arg1, arg2, arg3);
}

export function AlterWarehouseRename(arg1, arg2) {
  return window['go']['main']['App']['AlterWarehouseRename'](arg1, arg2);
}

export function AlterWarehouseResume(arg1) {
  return window['go']['main']['App']['AlterWarehouseResume'](arg1);
}

export function AlterWarehouseSuspend(arg1) {
  return window['go']['main']['App']['AlterWarehouseSuspend'](arg1);
}

export function AnalyzeMigration(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeMigration'](arg1, arg2);
}

export function AnalyzeSqlSemantics(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeSqlSemantics'](arg1, arg2, arg3);
}

export function AnalyzeSqlSyntax(arg1) {
  return window['go']['main']['App']['AnalyzeSqlSyntax'](arg1);
}

export function ApplySqlCasing(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplySqlCasing'](arg1, arg2, arg3, arg4);
}

export function CanCreateIntegration() {
  return window['go']['main']['App']['CanCreateIntegration']();
}

export function CanCreateUsers() {
  return window['go']['main']['App']['CanCreateUsers']();
}

export function CanManageUsers() {
  return window['go']['main']['App']['CanManageUsers']();
}

export function CanModifyUserAuth(arg1) {
  return window['go']['main']['App']['CanModifyUserAuth'](arg1);
}

export function CanViewWarehouseMeteringHistory() {
  return window['go']['main']['App']['CanViewWarehouseMeteringHistory']();
}

export function CancelChat() {
  return window['go']['main']['App']['CancelChat']();
}

export function CancelConnect() {
  return window['go']['main']['App']['CancelConnect']();
}

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function CancelMigration() {
  return window['go']['main']['App']['CancelMigration']();
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function CheckAvailableKeyTools() {
  return window['go']['main']['App']['CheckAvailableKeyTools']();
}

export function CheckPythonSyntax(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckPythonSyntax'](arg1, arg2, arg3);
}

export function CheckSnowparkEnv() {
  return window['go']['main']['App']['CheckSnowparkEnv']();
}

export function CloneChildTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CloneChildTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CloseTabSession(arg1) {
  return window['go']['main']['App']['CloseTabSession'](arg1);
}

export function ComputeJoinOnConditions(arg1) {
  return window['go']['main']['App']['ComputeJoinOnConditions'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateBackupPolicy(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateBackupPolicy'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateBackupSet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateBackupSet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateDbtProject(arg1, arg2) {
  return window['go']['main']['App']['CreateDbtProject'](arg1, arg2);
}

export function CreateMigrationSnapshot(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateMigrationSnapshot'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DebugNotebookCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['DebugNotebookCell'](arg1, arg2, arg3);
}

export function DeleteOldestBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteOldestBackup'](arg1, arg2, arg3);
}

export function DeleteVenvFolder() {
  return window['go']['main']['App']['DeleteVenvFolder']();
}

export function DeployNotebook(arg1) {
  return window['go']['main']['App']['DeployNotebook'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DropBackupPolicy(arg1) {
  return window['go']['main']['App']['DropBackupPolicy'](arg1);
}

export function DropBackupSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropBackupSet'](arg1, arg2, arg3);
}

export function DropIntegration(arg1) {
  return window['go']['main']['App']['DropIntegration'](arg1);
}

export function DropTaskTree(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropTaskTree'](arg1, arg2, arg3);
}

export function EnableTaskDependents(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnableTaskDependents'](arg1, arg2, arg3);
}

export function ExecDDL(arg1) {
  return window['go']['main']['App']['ExecDDL'](arg1);
}

export function ExecuteMigration(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteMigration'](arg1, arg2, arg3, arg4);
}

export function ExecuteNotebook(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteNotebook'](arg1, arg2, arg3, arg4);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function ExecuteTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteTask'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportAccountObjectsDDL(arg1) {
  return window['go']['main']['App']['ExportAccountObjectsDDL'](arg1);
}

export function ExportAllDatabasesDDL(arg1, arg2) {
  return window['go']['main']['App']['ExportAllDatabasesDDL'](arg1, arg2);
}

export function ExportDatabaseDDL(arg1, arg2) {
  return window['go']['main']['App']['ExportDatabaseDDL'](arg1, arg2);
}

export function ExportTableData(arg1) {
  return window['go']['main']['App']['ExportTableData'](arg1);
}

export function FetchNotebookContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchNotebookContent'](arg1, arg2, arg3);
}

export function FindSqlTokenPositions(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindSqlTokenPositions'](arg1, arg2, arg3);
}

export function GenerateKeyPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateKeyPair'](arg1, arg2, arg3);
}

export function GenerateMigrationScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateMigrationScript'](arg1, arg2, arg3);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAISuggestion(arg1) {
  return window['go']['main']['App']['GetAISuggestion'](arg1);
}

export function GetActiveFunctionCall(arg1) {
  return window['go']['main']['App']['GetActiveFunctionCall'](arg1);
}

export function GetAllDataTypes() {
  return window['go']['main']['App']['GetAllDataTypes']();
}

export function GetAllFunctionNames() {
  return window['go']['main']['App']['GetAllFunctionNames']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetColumnComments(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetColumnComments'](arg1, arg2, arg3);
}

export function GetCurrentRegion() {
  return window['go']['main']['App']['GetCurrentRegion']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDatabaseCrossDeps(arg1, arg2) {
  return window['go']['main']['App']['GetDatabaseCrossDeps'](arg1, arg2);
}

export function GetDatabaseRetentionDays(arg1) {
  return window['go']['main']['App']['GetDatabaseRetentionDays'](arg1);
}

export function GetDatabaseTableSummary(arg1) {
  return window['go']['main']['App']['GetDatabaseTableSummary'](arg1);
}

export function GetERDiagramData(arg1) {
  return window['go']['main']['App']['GetERDiagramData'](arg1);
}

export function GetEditorPrefs() {
  return window['go']['main']['App']['GetEditorPrefs']();
}

export function GetFeatureFlags() {
  return window['go']['main']['App']['GetFeatureFlags']();
}

export function GetFunctionInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFunctionInfo'](arg1, arg2, arg3, arg4);
}

export function GetFunctionSuggestions(arg1) {
  return window['go']['main']['App']['GetFunctionSuggestions'](arg1);
}

export function GetFunctionTooltip(arg1) {
  return window['go']['main']['App']['GetFunctionTooltip'](arg1);
}

export function GetGitConfig() {
  return window['go']['main']['App']['GetGitConfig']();
}

export function GetIdentifierAtColumn(arg1, arg2) {
  return window['go']['main']['App']['GetIdentifierAtColumn'](arg1, arg2);
}

export function GetIntegrationProperties(arg1) {
  return window['go']['main']['App']['GetIntegrationProperties'](arg1);
}

export function GetNotebookCompletions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetNotebookCompletions'](arg1, arg2, arg3, arg4);
}

export function GetNotebookHover(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetNotebookHover'](arg1, arg2, arg3, arg4);
}

export function GetNotebookPrefs() {
  return window['go']['main']['App']['GetNotebookPrefs']();
}

export function GetNotebookQueryWarehouse(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNotebookQueryWarehouse'](arg1, arg2, arg3);
}

export function GetObjectDDL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetObjectDDL'](arg1, arg2, arg3, arg4, arg5);
}

export function GetObjectDependencies(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetObjectDependencies'](arg1, arg2, arg3, arg4, arg5);
}

export function GetObjectProperties(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetObjectProperties'](arg1, arg2, arg3, arg4);
}

export function GetPipRegistryConfig() {
  return window['go']['main']['App']['GetPipRegistryConfig']();
}

export function GetProcedureParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetProcedureParams'](arg1, arg2, arg3, arg4);
}

export function GetQueryHistory(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['GetQueryHistory'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetQuotedIdentifiersIgnoreCase() {
  return window['go']['main']['App']['GetQuotedIdentifiersIgnoreCase']();
}

export function GetReservedKeywords() {
  return window['go']['main']['App']['GetReservedKeywords']();
}

export function GetRoleDDL(arg1) {
  return window['go']['main']['App']['GetRoleDDL'](arg1);
}

export function GetSchemaCrossDeps(arg1, arg2) {
  return window['go']['main']['App']['GetSchemaCrossDeps'](arg1, arg2);
}

export function GetSchemaForeignKeys(arg1, arg2) {
  return window['go']['main']['App']['GetSchemaForeignKeys'](arg1, arg2);
}

export function GetScriptingCompletions(arg1, arg2) {
  return window['go']['main']['App']['GetScriptingCompletions'](arg1, arg2);
}

export function GetSessionContext(arg1) {
  return window['go']['main']['App']['GetSessionContext'](arg1);
}

export function GetSessionParameters() {
  return window['go']['main']['App']['GetSessionParameters']();
}

export function GetSessionVariables() {
  return window['go']['main']['App']['GetSessionVariables']();
}

export function GetSnowflakeCLIConfigPath() {
  return window['go']['main']['App']['GetSnowflakeCLIConfigPath']();
}

export function GetSnowflakeKeywords() {
  return window['go']['main']['App']['GetSnowflakeKeywords']();
}

export function GetSnowparkConfig() {
  return window['go']['main']['App']['GetSnowparkConfig']();
}

export function GetSnowsightURL() {
  return window['go']['main']['App']['GetSnowsightURL']();
}

export function GetSqlStatementRanges(arg1) {
  return window['go']['main']['App']['GetSqlStatementRanges'](arg1);
}

export function GetSystemRAMGB() {
  return window['go']['main']['App']['GetSystemRAMGB']();
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function GetTableColumnsWithTypes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumnsWithTypes'](arg1, arg2, arg3);
}

export function GetTableForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableForeignKeys'](arg1, arg2, arg3);
}

export function GetTableRetentionDays(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableRetentionDays'](arg1, arg2, arg3);
}

export function GetTableSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSettings'](arg1, arg2, arg3);
}

export function GetTaskStatuses(arg1, arg2) {
  return window['go']['main']['App']['GetTaskStatuses'](arg1, arg2);
}

export function GetUserDDL(arg1) {
  return window['go']['main']['App']['GetUserDDL'](arg1);
}

export function GetWarehouseDDL(arg1) {
  return window['go']['main']['App']['GetWarehouseDDL'](arg1);
}

export function GetWarehouseMeteringHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWarehouseMeteringHistory'](arg1, arg2, arg3);
}

export function GetWarehouseParameters(arg1) {
  return window['go']['main']['App']['GetWarehouseParameters'](arg1);
}

export function GitCommitAndPush(arg1) {
  return window['go']['main']['App']['GitCommitAndPush'](arg1);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function ImportTableData(arg1) {
  return window['go']['main']['App']['ImportTableData'](arg1);
}

export function InitTabSession(arg1) {
  return window['go']['main']['App']['InitTabSession'](arg1);
}

export function InstallCondaEnv() {
  return window['go']['main']['App']['InstallCondaEnv']();
}

export function InstallEnvPackage(arg1) {
  return window['go']['main']['App']['InstallEnvPackage'](arg1);
}

export function InstallJupyterNotebook() {
  return window['go']['main']['App']['InstallJupyterNotebook']();
}

export function InstallJupyterVenv() {
  return window['go']['main']['App']['InstallJupyterVenv']();
}

export function InstallSnowparkPackage() {
  return window['go']['main']['App']['InstallSnowparkPackage']();
}

export function InstallSnowparkVenv(arg1) {
  return window['go']['main']['App']['InstallSnowparkVenv'](arg1);
}

export function InstallVenvEnv() {
  return window['go']['main']['App']['InstallVenvEnv']();
}

export function IsAppleSilicon() {
  return window['go']['main']['App']['IsAppleSilicon']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListAIModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAIModels'](arg1, arg2, arg3);
}

export function ListAvailableRoles() {
  return window['go']['main']['App']['ListAvailableRoles']();
}

export function ListBackupPolicies() {
  return window['go']['main']['App']['ListBackupPolicies']();
}

export function ListBackupSets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListBackupSets'](arg1, arg2, arg3, arg4, arg5);
}

export function ListBackups(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListBackups'](arg1, arg2, arg3);
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListDroppedDatabases() {
  return window['go']['main']['App']['ListDroppedDatabases']();
}

export function ListDroppedSchemas(arg1) {
  return window['go']['main']['App']['ListDroppedSchemas'](arg1);
}

export function ListDroppedTables(arg1, arg2) {
  return window['go']['main']['App']['ListDroppedTables'](arg1, arg2);
}

export function ListEnvPackages() {
  return window['go']['main']['App']['ListEnvPackages']();
}

export function ListExportableDatabases() {
  return window['go']['main']['App']['ListExportableDatabases']();
}

export function ListExternalVolumes() {
  return window['go']['main']['App']['ListExternalVolumes']();
}

export function ListFinalizableTasks(arg1, arg2) {
  return window['go']['main']['App']['ListFinalizableTasks'](arg1, arg2);
}

export function ListIntegrations(arg1) {
  return window['go']['main']['App']['ListIntegrations'](arg1);
}

export function ListNotificationIntegrations() {
  return window['go']['main']['App']['ListNotificationIntegrations']();
}

export function ListObjects(arg1, arg2) {
  return window['go']['main']['App']['ListObjects'](arg1, arg2);
}

export function ListRoles() {
  return window['go']['main']['App']['ListRoles']();
}

export function ListRootTasks(arg1, arg2) {
  return window['go']['main']['App']['ListRootTasks'](arg1, arg2);
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function ListSystemPythons() {
  return window['go']['main']['App']['ListSystemPythons']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function ListWarehouses() {
  return window['go']['main']['App']['ListWarehouses']();
}

export function LoadNotebookBreakpoints(arg1) {
  return window['go']['main']['App']['LoadNotebookBreakpoints'](arg1);
}

export function LoadSnowflakeCLIConfig() {
  return window['go']['main']['App']['LoadSnowflakeCLIConfig']();
}

export function MakeNotebookLive(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeNotebookLive'](arg1, arg2, arg3);
}

export function NewNotebook() {
  return window['go']['main']['App']['NewNotebook']();
}

export function NotebookUseContext(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['NotebookUseContext'](arg1, arg2, arg3, arg4, arg5);
}

export function ParseJoinTableRefs(arg1) {
  return window['go']['main']['App']['ParseJoinTableRefs'](arg1);
}

export function ParseSignatureParams(arg1) {
  return window['go']['main']['App']['ParseSignatureParams'](arg1);
}

export function PickCACertFile() {
  return window['go']['main']['App']['PickCACertFile']();
}

export function PickDataFile() {
  return window['go']['main']['App']['PickDataFile']();
}

export function PickDataFileByFormat(arg1) {
  return window['go']['main']['App']['PickDataFileByFormat'](arg1);
}

export function PickDataFilesByFormat(arg1) {
  return window['go']['main']['App']['PickDataFilesByFormat'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickNotebookFile() {
  return window['go']['main']['App']['PickNotebookFile']();
}

export function PickOpenFile() {
  return window['go']['main']['App']['PickOpenFile']();
}

export function PickSaveExportFile(arg1, arg2) {
  return window['go']['main']['App']['PickSaveExportFile'](arg1, arg2);
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function PickSnowflakeCLIConfigPath() {
  return window['go']['main']['App']['PickSnowflakeCLIConfigPath']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileHead(arg1, arg2) {
  return window['go']['main']['App']['ReadFileHead'](arg1, arg2);
}

export function ReadNotebook(arg1) {
  return window['go']['main']['App']['ReadNotebook'](arg1);
}

export function ResetPipRegistryConfig() {
  return window['go']['main']['App']['ResetPipRegistryConfig']();
}

export function ResizeShell(arg1, arg2) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2);
}

export function RestoreFromBackup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RestoreFromBackup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ResumeTaskList(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeTaskList'](arg1, arg2, arg3);
}

export function RunNotebookCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunNotebookCell'](arg1, arg2, arg3);
}

export function RunNotebookCellSql(arg1, arg2) {
  return window['go']['main']['App']['RunNotebookCellSql'](arg1, arg2);
}

export function RunNotebookSql(arg1) {
  return window['go']['main']['App']['RunNotebookSql'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveBinaryFile(arg1, arg2) {
  return window['go']['main']['App']['SaveBinaryFile'](arg1, arg2);
}

export function SaveEditorPrefs(arg1) {
  return window['go']['main']['App']['SaveEditorPrefs'](arg1);
}

export function SaveFeatureFlags(arg1) {
  return window['go']['main']['App']['SaveFeatureFlags'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveGitConfig(arg1) {
  return window['go']['main']['App']['SaveGitConfig'](arg1);
}

export function SaveNotebook(arg1, arg2) {
  return window['go']['main']['App']['SaveNotebook'](arg1, arg2);
}

export function SaveNotebookBreakpoints(arg1, arg2) {
  return window['go']['main']['App']['SaveNotebookBreakpoints'](arg1, arg2);
}

export function SaveNotebookPrefs(arg1) {
  return window['go']['main']['App']['SaveNotebookPrefs'](arg1);
}

export function SavePipRegistryConfig(arg1) {
  return window['go']['main']['App']['SavePipRegistryConfig'](arg1);
}

export function SaveSnowparkConfig(arg1) {
  return window['go']['main']['App']['SaveSnowparkConfig'](arg1);
}

export function SaveSnowparkPythonPath(arg1) {
  return window['go']['main']['App']['SaveSnowparkPythonPath'](arg1);
}

export function SaveSnowparkVenvPath(arg1) {
  return window['go']['main']['App']['SaveSnowparkVenvPath'](arg1);
}

export function ScanMigrationSource(arg1) {
  return window['go']['main']['App']['ScanMigrationSource'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SendChatMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SetColumnComment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetColumnComment'](arg1, arg2, arg3, arg4, arg5);
}

export function SetNotebookQueryWarehouse(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetNotebookQueryWarehouse'](arg1, arg2, arg3, arg4);
}

export function SetSessionParameter(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionParameter'](arg1, arg2, arg3);
}

export function SetSessionVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionVariable'](arg1, arg2, arg3);
}

export function SetUserPublicKey(arg1, arg2) {
  return window['go']['main']['App']['SetUserPublicKey'](arg1, arg2);
}

export function StartDapProxy() {
  return window['go']['main']['App']['StartDapProxy']();
}

export function StartNotebookSession(arg1) {
  return window['go']['main']['App']['StartNotebookSession'](arg1);
}

export function StartQuery(arg1, arg2) {
  return window['go']['main']['App']['StartQuery'](arg1, arg2);
}

export function StartShell(arg1, arg2) {
  return window['go']['main']['App']['StartShell'](arg1, arg2);
}

export function StopDapProxy() {
  return window['go']['main']['App']['StopDapProxy']();
}

export function StopNotebookSession(arg1) {
  return window['go']['main']['App']['StopNotebookSession'](arg1);
}

export function StopShell() {
  return window['go']['main']['App']['StopShell']();
}

export function SuggestImportOptions(arg1, arg2) {
  return window['go']['main']['App']['SuggestImportOptions'](arg1, arg2);
}

export function SuspendTaskGraph(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuspendTaskGraph'](arg1, arg2, arg3);
}

export function SuspendTaskList(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuspendTaskList'](arg1, arg2, arg3);
}

export function TaskHasChildren(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskHasChildren'](arg1, arg2, arg3);
}

export function TestAIModel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestAIModel'](arg1, arg2, arg3, arg4, arg5);
}

export function UninstallEnvPackage(arg1) {
  return window['go']['main']['App']['UninstallEnvPackage'](arg1);
}

export function UseDatabase(arg1, arg2) {
  return window['go']['main']['App']['UseDatabase'](arg1, arg2);
}

export function UseRole(arg1, arg2) {
  return window['go']['main']['App']['UseRole'](arg1, arg2);
}

export function UseSchema(arg1, arg2) {
  return window['go']['main']['App']['UseSchema'](arg1, arg2);
}

export function UseWarehouse(arg1, arg2) {
  return window['go']['main']['App']['UseWarehouse'](arg1, arg2);
}

export function ValidateBareColumnRefs(arg1) {
  return window['go']['main']['App']['ValidateBareColumnRefs'](arg1);
}

export function ValidateDataTypes(arg1, arg2) {
  return window['go']['main']['App']['ValidateDataTypes'](arg1, arg2);
}

export function ValidateSnowflakePatterns(arg1, arg2) {
  return window['go']['main']['App']['ValidateSnowflakePatterns'](arg1, arg2);
}

export function ValidateTablesExist(arg1) {
  return window['go']['main']['App']['ValidateTablesExist'](arg1);
}

export function VenvFolderExists() {
  return window['go']['main']['App']['VenvFolderExists']();
}

export function WaitForQueryResult(arg1) {
  return window['go']['main']['App']['WaitForQueryResult'](arg1);
}

export function WriteShell(arg1) {
  return window['go']['main']['App']['WriteShell'](arg1);
}
