// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {snowflake} from '../models';
import {main} from '../models';
import {ddl} from '../models';
import {config} from '../models';
import {gitrepo} from '../models';
import {filesystem} from '../models';
import {sfconfig} from '../models';
import {ai} from '../models';

export function CanCreateUsers():Promise<boolean>;

export function CanManageUsers():Promise<boolean>;

export function CancelConnect():Promise<void>;

export function CancelExport():Promise<void>;

export function CancelQuery():Promise<void>;

export function Connect(arg1:snowflake.ConnectParams):Promise<void>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<snowflake.QueryResult>;

export function ExportAccountObjectsDDL(arg1:string):Promise<main.AccountExportResult>;

export function ExportAllDatabasesDDL(arg1:string):Promise<Array<ddl.ExportResult>>;

export function ExportDatabaseDDL(arg1:string,arg2:string):Promise<ddl.ExportResult>;

export function ExportTableData(arg1:snowflake.ExportTableParams):Promise<snowflake.ExportTableResult>;

export function GetAIConfig():Promise<config.AIConfig>;

export function GetAISuggestion(arg1:string):Promise<string>;

export function GetERDiagramData(arg1:string):Promise<snowflake.ERDiagramData>;

export function GetFunctionInfo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<snowflake.FunctionInfo>;

export function GetGitConfig():Promise<config.GitConfig>;

export function GetObjectDDL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetObjectProperties(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.PropertyPair>>;

export function GetProcedureParams(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<snowflake.ProcParam>>;

export function GetRoleDDL(arg1:string):Promise<string>;

export function GetSessionContext():Promise<snowflake.SessionContext>;

export function GetTableColumns(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetTableRetentionDays(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetUserDDL(arg1:string):Promise<string>;

export function GetWarehouseDDL(arg1:string):Promise<string>;

export function GitCommitAndPush(arg1:gitrepo.PushParams):Promise<void>;

export function GitPull(arg1:gitrepo.PullParams):Promise<void>;

export function GitStatus(arg1:string):Promise<gitrepo.RepoStatus>;

export function ImportTableData(arg1:snowflake.ImportTableParams):Promise<snowflake.ImportTableResult>;

export function IsConnected():Promise<boolean>;

export function ListAIModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListAvailableRoles():Promise<Array<string>>;

export function ListDatabases():Promise<Array<string>>;

export function ListDirectory(arg1:string):Promise<Array<filesystem.FileEntry>>;

export function ListDroppedDatabases():Promise<Array<snowflake.DroppedTable>>;

export function ListDroppedSchemas(arg1:string):Promise<Array<snowflake.DroppedTable>>;

export function ListDroppedTables(arg1:string,arg2:string):Promise<Array<snowflake.DroppedTable>>;

export function ListNotificationIntegrations():Promise<Array<string>>;

export function ListObjects(arg1:string,arg2:string):Promise<Array<snowflake.SnowflakeObject>>;

export function ListRoles():Promise<Array<string>>;

export function ListSchemas(arg1:string):Promise<Array<string>>;

export function ListUsers():Promise<Array<snowflake.SnowflakeUser>>;

export function ListWarehouses():Promise<Array<string>>;

export function LoadSnowflakeCLIConfig():Promise<sfconfig.Config>;

export function PickDataFile():Promise<string>;

export function PickDataFileByFormat(arg1:string):Promise<string>;

export function PickDirectory():Promise<string>;

export function PickOpenFile():Promise<string>;

export function PickSaveExportFile(arg1:string,arg2:string):Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveAIConfig(arg1:config.AIConfig):Promise<void>;

export function SaveBinaryFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveGitConfig(arg1:config.GitConfig):Promise<void>;

export function SearchFiles(arg1:string,arg2:string,arg3:boolean):Promise<Array<filesystem.SearchMatch>>;

export function SendChatMessage(arg1:Array<ai.UIMessage>,arg2:string,arg3:string,arg4:string):Promise<Array<ai.UIMessage>>;

export function StartQuery(arg1:string):Promise<string>;

export function UseRole(arg1:string):Promise<void>;

export function UseWarehouse(arg1:string):Promise<void>;

export function WaitForQueryResult():Promise<snowflake.QueryResult>;
