// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelConnect() {
  return window['go']['main']['App']['CancelConnect']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function ExportAllDatabasesDDL(arg1) {
  return window['go']['main']['App']['ExportAllDatabasesDDL'](arg1);
}

export function ExportDatabaseDDL(arg1, arg2) {
  return window['go']['main']['App']['ExportDatabaseDDL'](arg1, arg2);
}

export function GetGitConfig() {
  return window['go']['main']['App']['GetGitConfig']();
}

export function GetObjectDDL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetObjectDDL'](arg1, arg2, arg3, arg4);
}

export function GitCommitAndPush(arg1) {
  return window['go']['main']['App']['GitCommitAndPush'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListObjects(arg1, arg2) {
  return window['go']['main']['App']['ListObjects'](arg1, arg2);
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function LoadSnowflakeCLIConfig() {
  return window['go']['main']['App']['LoadSnowflakeCLIConfig']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function SaveGitConfig(arg1) {
  return window['go']['main']['App']['SaveGitConfig'](arg1);
}
