// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sfconfig} from '../models';
import {snowflake} from '../models';
import {ddl} from '../models';
import {config} from '../models';
import {gitrepo} from '../models';

export function CancelConnect():Promise<void>;

export function Connect(arg1:snowflake.ConnectParams):Promise<void>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<snowflake.QueryResult>;

export function ExportAllDatabasesDDL(arg1:string):Promise<Array<ddl.ExportResult>>;

export function ExportDatabaseDDL(arg1:string,arg2:string):Promise<ddl.ExportResult>;

export function GetGitConfig():Promise<config.GitConfig>;

export function GetObjectDDL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GitCommitAndPush(arg1:gitrepo.PushParams):Promise<void>;

export function GitStatus(arg1:string):Promise<gitrepo.RepoStatus>;

export function IsConnected():Promise<boolean>;

export function LoadSnowflakeCLIConfig():Promise<sfconfig.Config>;

export function ListDatabases():Promise<Array<string>>;

export function ListObjects(arg1:string,arg2:string):Promise<Array<snowflake.SnowflakeObject>>;

export function ListSchemas(arg1:string):Promise<Array<string>>;

export function PickDirectory():Promise<string>;

export function SaveGitConfig(arg1:config.GitConfig):Promise<void>;
